### ISSUE TITLE
Tampilkan kode desa (readonly) di form pelanggan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#10]
Kode desa diperlukan untuk cross-check pada waktu pengisian Info Desa > Identitas Desa di OpenSID, karena itu yg digunakan untuk mengambil data dari Layanan. Tampilkan kode desa setelah memilih Desa.

**Comment by agungsugiarto** [comment]
Sudah di master melalui commit https://github.com/OpenSID/Layanan_OpenDESA/commit/ab73697b86cd1dc58add130ec6861b5b41774365
