### ISSUE TITLE
Anjungan (daftar permintaan -- tutup setelah dibuat issue2 terpisah)

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-layanan-opendesa#100]
Selain layanan mengonlinekan OpenSID, opendesa juga memiliki layanan non teknis seperti Anjungan Desa Mandiri. tp kendalanya banyak pihak luar yang tidak bekerja sama menjual produk serupa sehingga pesanan ke OpenDesa berkurang. olehnya perlu ditambahakan token sebagai lisensi untuk setiap perangkat anjungan. Anjungan yang dibeli melalui penyedia lain harus membeli lisensi kepada OpenDesa. 

Diharapkan :
Anjungan yang tidak berlisensi hanya terbaca sebagai layanan mandiri biasa, login pakai KTP-El tetap harus memasukkan PIN. dan permohonan surat harus memasukkan persyaratan.

**Comment by ai-skematik** [comment]
Layanan OpenDesa

- [x] 1. Tambahakan Token Anjungan di Layanan OpenDesa
- [x]  2. Tambahkan Pelanggan dari Non Desa
- [x] 3. Tambahkan Pilihan Faktur ditampilkan di Desa atau Tidak
- [x] 4. Tambahakn fitur lisensi tema Anjungan

OpenSID
- [x] 1. Tambahkan fitur pengaturan tema Anjungan Desa Mandiri
- [x] 2. Pengaturan tema anjungan hanya aktif ketika memiliki lisensi anjungan
- [x] 3. Ubah cara membaca Perangkat Anjungan dengan menggunakan ID Browser
- [x] 4. tambahkan fitur buku tamu dan hanya terlihat di anjungan

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/OpenSID/issues/5406

**Comment by eddieridwan** [comment]
@yogiperdana @vickyrolanda @FirlianiF : batasi issue ini HANYA untuk memastikan di OpenSID perangkat anjungan hanya diaktifkan jika desa ybs ada pemesanan anjungan yg sudah difinalkan. Yaitu tampilan khusus anjungan tidak diperlihatkan kalau desa tidak memiliki pemesanan anjungan. Dalam hal ini tampilkan layanan mandiri biasa.

Harap semua fitur2 yg lain di komentar di atas dibuatkan issue2 terpisah dan komentar di atas dihapus, supaya tidak membingungkan.

**Comment by yogiperdana** [comment]
> @yogiperdana @vickyrolanda @FirlianiF : batasi issue ini HANYA untuk memastikan di OpenSID perangkat anjungan hanya diaktifkan jika desa ybs ada pemesanan anjungan yg sudah difinalkan. Yaitu tampilan khusus anjungan tidak diperlihatkan kalau desa tidak memiliki pemesanan anjungan. Dalam hal ini tampilkan layanan mandiri biasa.
> 
> Harap semua fitur2 yg lain di komentar di atas dibuatkan issue2 terpisah dan komentar di atas dihapus, supaya tidak membingungkan.

Terkait validasi sudah dibuatkan issuenya dari minggu lalu pak https://github.com/OpenSID/OpenSID/issues/5501

**Comment by yogiperdana** [comment]
Untuk poin lainnya saat ini juga dimasukkan di project opensid 22.09 pak? Atau hanya issue validasi saja yang dimasukkan

**Comment by eddieridwan** [comment]
DImasukkan juga ke project sebagai Diprioritaskan.

**Comment by yogiperdana** [comment]
Baik sudah ditambahkan pak. Sekalian saya buatkan modul khsusu anjungan

**Comment by eddieridwan** [comment]
Issue ini ditutup, karena sudah dibuatkan issue terpisah untuk setiap permintaan di issue ini.
