### ISSUE TITLE
Sediakan Api untuk pendaftaran kerjasama OPENDK

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-layanan-opendesa#103]
variable :
- Email
- Status Registrasi /Langganan
- Kode kecamatan
- Domain kecamatan
- Nama Kontak
- No HP. Kontak
- Unggah Dokumen Yang Telah Ditandatangani (format .pdf)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/269
