### ISSUE TITLE
BUG : Layanan belum lunas tapi terdeteksi sudah aktif

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#106]
sebagai informasi,
walaupun sampai dengan saat ini di Layanan status Belum Lunas.

Tetapi di halaman admin desa, Layanan sudah terdeteksi dan aktif hingga 2023.
![photo_2022-06-17_09-29-46](https://user-images.githubusercontent.com/30171560/174213046-c7b88370-5789-4151-a312-581347d3b374.jpg)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/88
