### ISSUE TITLE
Aktifkan tombol untuk menyalin token ke clipboard di form Pelanggan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#11]
Saat ini tombol di form Pelanggan untuk menyalin token ke clipboard tidak aktif. Tombol ini perlu diaktifkan untuk memudahkan mengambil token untuk dikirim ke pelanggan atau memasukkan ke pengaturan aplikasi.

**Comment by agungsugiarto** [comment]
Sudah di merge ke master melalui pr https://github.com/OpenSID/Layanan_OpenDESA/pull/1
