### ISSUE TITLE
BUG: premium tidak aktif padahal harusnya bulan tersebut masih bisa digunakan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#113]
contoh langganan premium tgl akhir nya 23 juni, tapi tanggal 24 sudah tidak dapat digunakan, harusnya langganan masih dapat digunakan sampai 31 juni

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/94
