### ISSUE TITLE
OPENSID: Tambahkan Pengecekan dan validasi saat desa akan melakukan migrasi database ke versi terbaru

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#118]
Nantinya di opensid nya perlu pengecekan/verifikasi saat lakukan migrasi database yg otomatis. Apakah langganannya sdh berakhir atau belum ? Jika sudah berkahir, maka tampilkan notifikasi kalau tidak bisa upgrade versi opensid karena sdh habis masa langganannya.

* Penjelasannya itu adalah soal lupa upgrade, padahal premium sudah habis. Diberikan penghalang ketika upgrade ke versi yg tidak seharusnya (di atasnya), cukup diberi peringatan saja Dan batalkan. Jadi tidak sempat terjadi migrasi database.
Sehingga ketika di downgrade bisa digunakan lagi.

https://github.com/OpenSID/wiki-layanan-opendesa/issues/112

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/blob/cb7227b552f4a5aaa6cb8ae28aad9f40f185d603/donjo-app/models/Database_model.php#L3567
