### ISSUE TITLE
Perbaiki judul dan urutan Laporan Kabupaten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#121]
Laporan ini sebenarnya hanya terbatas pada pelanggan premium. Tujuannya untuk mengetahui sekilas perkembangan pelanggan premium. Termasuk kabupaten mana yg telah mencapai lebih dari 100 pelanggan.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/249563/177273228-9775c7af-3fb0-456a-9238-113490b24e9f.png">

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/96
