### ISSUE TITLE
Jumlah pelanggan bulan ini menghitung pemesanan bulan lalu

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#127]
Di layanan.opendesa.id, buka halaman seperti di gambar di bawah: 

![telegram-cloud-photo-size-5-6285325875239039359-y](https://user-images.githubusercontent.com/249563/182062986-4fff04f4-468f-42bf-be8d-d49d57714240.jpg)

Laporan di atas dibuat pada tanggal 1 Agustus 2022. Pemesanan yg dilaporkan sebenarnya dimasukkan pada bulan Juli. 

Masalah serupa juga terlihat di menu lain, seperti di Laporan > Laporan Layanan:
'
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/249563/182064064-078722c1-7dea-4b7b-ab1d-1943e93c609e.png">

**Comment by FirlianiF** [comment]
Issue ini sudah diperbaiki sebelumnya. Berikut hasil pengecekannya dan telah sesuai.

**Laporan Layanan Bulan Ini**
![laporan layanan](https://user-images.githubusercontent.com/30171560/194200728-250352bd-794f-4571-ac04-2ea7ddd8fc54.PNG)

**Laporan Pelanggan Bulan Ini**
![laporan pelanggan](https://user-images.githubusercontent.com/30171560/194200795-be877597-e919-4bc7-820e-072947be3943.PNG)

**Screen Shoot Invoicenya**
![inv4](https://user-images.githubusercontent.com/30171560/194200886-dc3cec44-8e0d-4343-bf2e-5f2d97e6b2a3.PNG)
![inv3](https://user-images.githubusercontent.com/30171560/194200895-1c968e71-9e6d-4f44-b7e5-98e395cb2542.PNG)
![inv2](https://user-images.githubusercontent.com/30171560/194200898-db14702c-a595-49c0-88b0-913ea4d86a43.PNG)
![inv1](https://user-images.githubusercontent.com/30171560/194200902-d30d0911-22ad-4f39-ac9c-41c3205d0bfd.PNG)

**Comment by FirlianiF** [comment]
Pak @eddieridwan mau memastikan kembali, yang tampil di laporan pelanggan dan laporan layanan itu berdasarkan tanggal dibuat pemesanan atau tanggal mulai pemesanan tersebut?

**Comment by devrakapriyo** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/139
