### ISSUE TITLE
Perbaiki pilih layanan ketika tambah layanan lebih dari 3 layanan, maka langsung pindah posisi

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#135]
![pilih layanan](https://user-images.githubusercontent.com/30171560/183575522-ed9be6e1-9656-4f15-9150-75fbd5e27cb6.PNG)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/110
