### ISSUE TITLE
Ubah tanggal mulai/akhir pemesanan anjungan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#15]
Tambah/Ubah tanggal mulai dan tanggal akhir pemesanan untuk kasus pemesanaan anjungan menjadi tanggal pesan dan tanggal kirim.

**Comment by FirlianiF** [comment]
tanggal kirim itu dapat di ubah, karena saat buat pesanan di awal belum dapat di presiksi kapan dikirim.

fyi: dapat berkaitan dengan issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/155

**Comment by habibie11** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/282
