### ISSUE TITLE
Kode Aktifasi tema pro

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#159]
Issue  ini berkaitan dengan issue https://github.com/OpenSID/wiki-saas/issues/100, yaitu mengirimkan inputan berupa aktivasi tema pro dari layanan.

Catatan:
Untuk Aktifasi tidak perlu disimpan di database cukup mengirimkan ke OpenSID SiapPakai.
API menggunakan {{host}}/api/memasang-tema-pro

**Comment by FirlianiF** [comment]
Mas @scqolbu24 tolong beritahukan disini data-data apa saja yang harus ditambahkan saat mengirim request untuk pemasangan tema pro ini.

**Comment by FirlianiF** [comment]
biasanya:
config kode aktivasi
config kode kota jadwal sholat
config kode ip
config warna tema
config fluid
config menu
config logo
config fbappid
config fbadmin

NB:
- fluid, menu, logo, menggunakan true/false
- yang lainnya text

**Comment by scqolbu24** [comment]
Ada perubahan mba @FirlianiF sesuai dengan issue https://github.com/OpenSID/wiki-saas/issues/102, perlu disimpan di database sehingga mempermudah ketika update.
tambahan pada tabel `tema_saas`

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/138
