### ISSUE TITLE
Bisa tambahkan item biaya pada pemesanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#16]
Untuk pemesanan anjungan dan mungkin nanti pemesanan barang fisik lainnya, akan dibutuhkan item biaya tambahan, seperti ongkir, packing, biaya muat, dll. Item biaya ini perlu bisa ditambahkan ke pemesanan dan terhitung di dalam faktur.

Harga item biaya tidak tentu, jadi perlu bisa diisi bebas pada waktu membuat pemesanan. 

Jadi fitur yg diperlukan adalah:
1. bisa membuat item biaya
2. pada waktu pemesanan bisa menambahkan item biaya ke pemesanan, dan bisa mengisi nilainya
3. pada faktur pemesanan, semua item biaya ikut terhitung pada total jumlah faktur.

**Comment by FirlianiF** [comment]
catatan dari pak ariandi:
tipe item biaya -> harga layanan pada pemesanan bisa di edit
tipe default -> harga layanan pada pemesanan di disable/readonly

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/151
