### ISSUE TITLE
duplikasi email pendaftaran kerjasama

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#160]
Cek issue https://github.com/OpenSID/OpenSID/issues/5672

Notifikasi hanya tercatat di log, tanpa mengirim respon error tsb ke OpenSID.

![192194369-d1dee218-cfc6-47f6-801c-c46748299d85](https://user-images.githubusercontent.com/57283157/193501769-764672ed-a83f-40b8-8a7c-aa1ad02df935.jpg)

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/140

**Comment by devrakapriyo** [comment]
https://github.com/OpenSID/Layanan_OpenDESA/pull/142
