### ISSUE TITLE
Pisahkan tabel untuk rincian pemesanan khusus untuk pemesanan premium dan pemesanan lainnya (selain premium)

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#163]
OPENSID: https://github.com/OpenSID/OpenSID/issues/5828
PR: https://github.com/OpenSID/premium/pull/1477

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1477
