### ISSUE TITLE
Penyesuaian Panduan Penggunaan OpenSID Siap Pakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#168]

**Comment by scqolbu24** [comment]
- [ ] ERD: tema_konfigurasi, pelanggan
- [ ] Halaman Administrasi

**Comment by scqolbu24** [comment]
![Dasbor](https://user-images.githubusercontent.com/68048807/221396262-b0629aea-a1aa-4068-85e1-3f91a1e4addb.png)

**Comment by FirlianiF** [comment]
https://panduan.opendesa.id/id/layanan-opendesa/halaman-administrasi
