### ISSUE TITLE
[Tanya Jawab] Status Aktif / Tidak Aktif (Pak AI)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#17]
Status Aktif / Tidak Aktif pelanggan secara otomatis diambil dari tanggal awal sampai tanggal berakhir.

Pak @ai-skematik, apa benar bgni???

**Comment by ai-skematik** [comment]
status aktif jika tanggal berlanggan belum berakhir., jd yg jadi acuan tanggal berakhir.

**Comment by agungsugiarto** [comment]
Iya ini terkendala, event di database karena dibatasi. Terpaksa harus merubah manual dipelanggan.

**Comment by FirlianiF** [comment]
Sebagai informasi :
Status pada pelanggan (aktif, tidak aktif, suspend, menunggu verifikasi email, menunggu verifikasi dokumen pendaftaran, terdaftar) itu merupakan status pendaftaran kerjasama yang dilakukan oleh pengguna.
status aktif merupakan default saat pelaksana membuat data pelanggan.
