### ISSUE TITLE
Pemilihan Tema

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#170]
- [x] Ketika Pemesanan tema dibarengkan dengan OpenSID SiapPakai pada inputan `Pemesanan` di Form OpenSID Siap Pakai Pasang Tema Pro saat ini belum tampil.

Filter :
- [x] Daftar tema ditampilkan jika ada pemesanan.
- [x] Faktur pemesanan tampil jika ada pemesanan tema didalamnya

- [x] Dibuat keterangan per masing-masing inputan pada tema configurasi
- [x] Tema silir: ditambahkan form kode_kota sesuai dengan kode kota denatra

**Keterangan pada form:** 
$config['ip_address'] = 'ketik_ip_address'; //Tampilkan Halaman Anjungan

$config['color'] = 'primary'; //Pilih salah satu untuk ubah warna tampilan: primary, success, warning, danger, atau secondary

$config['fluid'] = true; //Tampilkan Halaman Penuh

$config['menu'] = true; //Tampilkan Menu di Header

$config['logo'] = true; //Logo saat bagikan link web utama dari file : desa/themes/denatra/assets/image/logo.png

$config['fbadmin'] = '1117950751'; //Pengaturan Komentar Facebook

$config['fbappid'] = '147912828718'; //Pengaturan Komentar Facebook

$config['kode_kota'] = '2207'; //Pengaturan Jadwal Sholat -> 

- [x] AMBIL DARI DATA KABUPATEN (SELECT)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/146
