### ISSUE TITLE
Fitur Api Wilayah hanya menampilkan pelanggan premium

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-layanan-opendesa#172]
saat ini Api Wilayah pada layanan menampilkan pelanggan premium maupun umum.

yang di inginkan  :
hanya menampiklan pelanggan umum.

**Comment by eddieridwan** [comment]
@FirlianiF @apidong di aplikasi mobile, daftar pilihan desa seharusnya hanya desa yg berlangganan Premium.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/145
