### ISSUE TITLE
Buat pilihan saat input API domain desa di form input pelanggan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#174]
crud pelanggan
- API domain Desa dibuat button (hosting biasa / OpenSID Siap Pakai)

jika hosting biasa maka inputan API domain desa dapat di isi
jika opensid siap pakai maka API domain desa disable

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/187
