### ISSUE TITLE
Meringkas/menyederhanakan proses pencatatan layanan

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#18]
Saat ini saat kita melakukan pencatatan layanan, langkah yg kita lakukan total ada 4.
mulai dari input kontak, pengguna, pelanggan hingga terakhir pesanan.
langkah ini menurut saya bisa disederhanakam jadi 2 saja. yaitu pembuatan pelanggan dijadikan satu dengan pembuatan akun/pengguna dan juga info kontak 
dan satu pengguna bisa memiliki beberapa pesanan layanan.
mirip client area hosting

**Comment by eddieridwan** [comment]
Mohon perhatikan, bahwa `pengguna` berbeda dgn `pelanggan`. Pelanggan kita adalah `desa`, bukan individu/orang. `Pengguna` adalah `orang`. Pengguna bisa siapa saja yg kita berikan akses pada Layanan, termasuk pelaksana, pengurus, pendamping desa, kontak dan lainnya.

Jadi konsep Layanan OpenDesa sangat berbeda dengan client area hosting yg tidak mempunyai konsep`desa`. 

Kita berhubungan dengan desa sebagai pelanggan. Pengguna (orang) bisa berubah untuk suatu desa -- ingat satu desa bisa memiliki beberapa kontak (pengguna). Dan pengguna tidak harus merupakan kontak bagi suatu desa (pelanggan).

jadi untuk penyederhaan, harus melihat cara lain. Tidak dengan menggabungkan konsep kontak/pengguna/pelanggan.

Saya rangkum:
1. **Pelanggan** adalah desa
2. **Pengguna** adalah orang yg kita beri akses pada Layanan. Bisa pelaksana, pengurus, kontak, dll
3. **Kontak** adalah orang yg bisa kita hubungi terkait desa pelanggan. Kontak tidak harus menjadi pengguna.
4. **Pelaksana** adalah pengguna yg mempunyai hak akses membuat/mengubah pelanggan/pemesanan

**Comment by roaddee** [comment]
berarti kit perlu sederhanakan kontak saja, untuk mengurangi langkah pendaftaran yg cukup panjang. nanti bisa kita review lagi sambil berjalan

**Comment by eddieridwan** [comment]
Kontak tidak harus menjadi pengguna. Jadi data yg diisi untuk kontak bisa disederhanakan, dan bisa dilakukan pada saat membuat pelanggan, karena setiap pelanggan **harus** memiliki sedikitnya satu kontak.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, idealnya adalah satu pengguna untuk satu pelanggan.

**Comment by eddieridwan** [comment]
@agungsugiarto Pelanggan belum tentu ada penggunanya Cukup ada kontak. Bisa lebih dari satu kontak. Kontak minimal ada nomor HP, tapi tidak harus ada email. Sekali lagi, pelanggan adalah desa  Pengguna belum tentu ada hubungan dgn desa tertentu. Pengguna adalah orang yg bisa akses Layanan.

**Comment by eddieridwan** [comment]
Yang berhubungan dengan desa adalah kontak. Sekali lagi, kontak tdk perlu menjadi pengguna.

**Comment by agungsugiarto** [comment]
Pengguna wajib diisi dipelanggan pak, untuk digunakan sebagai autentikasi ketika mengakses api.

**Comment by eddieridwan** [comment]
Perlu ditinjau ulang. Kita bicarakan di Slack.

**Comment by agungsugiarto** [comment]
> Yang berhubungan dengan desa adalah kontak. Sekali lagi, kontak tdk perlu menjadi pengguna.

Iya kontak dan pengguna adalah berbeda, tidak ada relasinya, tapi pengguna (user) beralasi dengan pelanggan. Bisa dilihat di ERD pak,

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/wiki-layanan-opendesa/issues/3

**Comment by FirlianiF** [comment]
Duplikat issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/3
