### ISSUE TITLE
Perbaiki laporan layanan agar tidak ada data layanan duplikat

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#180]
untuk kasus kategori, layanan, harga nya sama. jika ketiganya sama maka bisa digabungkan data nya di laporan layanan.

**Comment by FirlianiF** [comment]
menggabungkan semua jenis layanan Premium, supaya tinggal satu saja di laporan

**Comment by FirlianiF** [comment]
cek OpenSID SiapPakai - OpenSID SaaS

**Comment by devrakapriyo** [comment]
PR https://github.com/OpenSID/Layanan_OpenDESA/pull/168
