### ISSUE TITLE
Pada laporan layanan tambahkan tombol pada jumlah pemesanan untuk masuk ke halaman pemesanan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#183]
ketika di klik, masuk ke halaman pemesanan lalu tampilkan data pemesanan sesuai dengan laporan yang di klik

**Comment by devrakapriyo** [comment]
PR https://github.com/OpenSID/Layanan_OpenDESA/pull/169
