### ISSUE TITLE
Satu Pelanggan bisa dengan dua Pelaksana

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#19]
Sehubungan dengan adanya pelaksana anjungan yang berbeda dengan pelaksana layanan hosting, mengakibatkan adanya kemungkinan terjadi terdapat 1 desa/pelanggan bisa memiliki dua (2) akun di layanan.opendesa.id, dikarenakan dimasukkan oleh 2 pelaksana yaitu pelaksana anjungan dan pelaksana hosting.

yang diharapkan adalah ada pemisahan antara 2 pelaksana, namun pelanggan tetap satu

**Comment by andifahruddinakas** [comment]
Dari kasus ini, apa sebaiknya pelaksana melekat di pemesanan pak @eddieridwan, @roaddee ???

**Comment by eddieridwan** [comment]
@afa28 , tetap di pelanggan. Karena relasi antara pemesanan dan pelaksana tidak tentu. Misalnya:
1. Pemesanan ajungan+premium --> dua pelaksana
2. Pemesanan perpanjangan hosting --> pelaksana hosting yg semula

Relasi yg tentu adalah adanya beberapa pelaksana per pelanggan, yg individunya tergantung sikon.

**Comment by andifahruddinakas** [comment]
ini bisa di tutup
