### ISSUE TITLE
Membatalkan Langganan SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#196]
Membatalkan atau menghapus jika pemesanan bukan SiapPakai

**Comment by FirlianiF** [comment]
mas @scqolbu24 boleh tolong dijelaskan mas kebutuhan dan alurnya seperti apa mas??

**Comment by scqolbu24** [comment]
mba @FirlianiF,penjelasannya seperti berikut:
Ketika terdapat pelanggan yang sudah diinstall pada server SiapPakai, kemudian pelanggan tersebut membatalkan langganan maka perlu dihapus semua data atau folder yang berkaitan dengan pelanggan tersebut.

Caranya adalah mendeteksi bahwa desa tersebut tidak ada pemesanan SiapPakai, kemudian kirimkan batalkan melalui API ke server SiapPakai yang sebelumnya telah didaftarkan, contoh desa https://babang.opendesa.id/.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/158
