### ISSUE TITLE
Tambahkan Kolom Pemesanan dan Cara Melihat Pemesananya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#197]
Pada table OpenSID Siap Pakai ditambahkan kolom pemesanan dan tombol untuk melihat pemesannya.

**Comment by FirlianiF** [comment]
mas @scqolbu24 boleh tolong dijelaskan mas kebutuhan dan alurnya seperti apa mas?

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/157
