### ISSUE TITLE
Pelanggan bisa mengganti token yg diperbaharui secara otomatis

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#20]
Saat ini setiap kali token pelanggan diperbaharui (setelah pemesanan baru), token tersebut disalin dan diberikan kepada pelanggan secara manual untuk dimasukkan ke pengaturan OpenSID.

Diperlukan fitur yg memungkinkan OpenSID secara otomatis mengganti token layanan yg sdh diperbaharui dengan token yg baru, jika ada.

**Comment by agungsugiarto** [comment]
Prosesnya tidak bisa dilakukan seperti itu pak @eddieridwan, karena jika token sudah kadaluarsa otomatis tidak bisa melakukan autentikasi ke layanan.opendesa.id

Alternatif:
Pelanggan desa diberikan email + password, jadi mereka bisa generate token mereka sendiri sama seperti opensid melakukan sinkronasi  ke opendk,

**Comment by eddieridwan** [comment]
Sesuaikan saja supaya bisa. Misalnya:
1. untuk otentikasi, simpan token sebelumnya saat membuat token baru, atau hanya gunakan bagian login usernya saja.
2. pada saat OpenSID mengakses Layanan, periksa token yg dikirim. Kalau ada token yg baru kirim balik
3. di OpenSID, ganti token kalau ada kiriman token baru.

Sebaiknya kita hindari pelanggan akses ke Layanan.

**Comment by agungsugiarto** [comment]
Kalau maksud bapak mengganti token yg diperbahrui, solusinya simple sepertinya pak
1. Cek apakah response token != dengan token yg disimpan di opensid maka simpan response token yg baru.

Kalau expired token bukan seperti ini metodenya.

> Sesuaikan saja supaya bisa. Misalnya:
> 
> 1. untuk otentikasi, simpan token sebelumnya saat membuat token baru, atau hanya gunakan bagian login usernya saja.
> 2. pada saat OpenSID mengakses Layanan, periksa token yg dikirim. Kalau ada token yg baru kirim balik
> 3. di OpenSID, ganti token kalau ada kiriman token baru.
> 
> Sebaiknya kita hindari pelanggan akses ke Layanan.

**Comment by eddieridwan** [comment]
Silakan menggunakan cara terbaik. Yg penting, tidak manual. Dan tidak memerlukan pelanggan melakukan hal khusus. Juga perlu tetap aman.
