### ISSUE TITLE
OPENSID: perbarui validasi cetak faktur

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#208]
![photo_2022-11-14_14-32-29](https://user-images.githubusercontent.com/30171560/201600788-f5f706d9-8962-4639-9cea-0e55f8d271ee.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1603
