### ISSUE TITLE
Perbaiki layanan belum lunas karena ingin buat invoive awal, namun gagal.

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#211]
layanan belum lunas karena ingin buat invoive awal, namun gagal.

karena seharusnya memang belum lunas belum ada nota.

**Comment by FirlianiF** [comment]
![photo_2022-11-17_13-26-08](https://user-images.githubusercontent.com/30171560/202422678-ad7de575-9b02-40ad-b49d-3b28b93205ff.jpg)

**Comment by devrakapriyo** [comment]
PR https://github.com/OpenSID/Layanan_OpenDESA/pull/170
