### ISSUE TITLE
Fitur: Tambah status perpanjang pada pemesanan untuk mendeteksi pemesanan tsb sudah dilakukan perpanjangan atau belum.

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#219]
di pelanggan saya juga masih rancu saat filter Sebentar Lagi Berakhir. niatnya ingin membuat reminder.

ketika diklik cari, banyak yg sudah perpanjang. walaupun betul ada invoice yg memang hampir berakhir.

**Comment by ariandii** [comment]
ketika warna baterai berubah, maka notifikasi juga perlu muncul.

warna baterai ada 3 jenis. hijau, orange dan merah

jika merah, tentu sudah berakhir, dengan demikian menurut saya waktu "Sebentar Lagi berakhir" sesuai dengan warna orange pada baterai.

=====
untuk studi kasusnya, bisa dicoba, berapakah desa yang Sebentar Lagi berakhir saat ini?
(yg benar benar akan berakhir, bukan termasuk yang sudah diperpanjang)

contoh berakhir tanggal 25 desember nanti, namun ternyata sudah diperpanjang kemaren,

sehingga ada 2 invoice, 1 lama mau berakhir, 1 baru perpanjang.

maka itu tidak perlu dimunculkan dalam list "Sebentar Lagi Berakhir"

yg perlu muncul, hanya jika akan berakhir dan belum ada perpanjangan.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/188
