### ISSUE TITLE
Cek hasil laporan layanan terjadi selisih bulan ini dan nota bulan ini

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#221]
contoh, batuah, buln lalu real 93. tapi tercatat di laynan hanya 38.

begitu juga dengan silir 9, tercatat hanya 2 di laporan layanan.

**Comment by devrakapriyo** [comment]
https://github.com/OpenSID/Layanan_OpenDESA/pull/189
