### ISSUE TITLE
Tambahkan kolom jumlah pengguna server OpenSID SiapPakai

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#229]
![photo_2022-12-15_13-00-16](https://user-images.githubusercontent.com/30171560/210297967-9073f7e8-b9f5-4fe4-b916-3ceeeb4bf001.jpg)

untuk di halaman ini, bisa ditambahkan kolom jumlah pengguna server tersebut

yg jika diklik akan mengarah ke halaman siappakai dengan server tersebut.

**Comment by scqolbu24** [comment]
Untuk jumlah server dari luar / kabupaten / kota dapat menggunakan select berdasarkan kode kabupaten yang memiliki token atal berlangganan premium.

Issue terpisah: https://github.com/OpenSID/wiki-layanan-opendesa/issues/253

**Comment by FirlianiF** [comment]
> Untuk jumlah server dari luar / kabupaten / kota dapat menggunakan select berdasarkan kode kabupaten yang memiliki token atal berlangganan premium.
> 
> Issue terpisah: #253

mas @scqolbu24 kode kab nya didapat dari mana ya? karena data server tidak menyimpan kode kab/kota, hanya ada keterangan jenis server luar saja

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/197
