### ISSUE TITLE
Tambahkan filter 'bulan sebelumnya' untuk daftar Pelanggan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#23]
Laporan pelanggan baru bulan sebelumnya diperlukan untuk pembagian hasil tema premium, dan untuk pembayaran honor pelaksana. 

Issue ini untuk menambahkan filter supaya bisa menampikan daftar jenis layanan tertentu yg baru pada bulan sebelumnya.

**Comment by andifahruddinakas** [comment]
Bisa di close
