### ISSUE TITLE
Cek dan perbaiki hasil Laporan Premium Per Kabupaten

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#230]
![pree](https://user-images.githubusercontent.com/30171560/210298115-17cda2c9-a420-42c8-92fe-6206077e3972.jpg)

sepertinya Laporan Premium salah. Dilaporkan Pelanggan Premium ada 7. Tetapi juga dilaporkan jumlah baru bulan ini 11 dan bulan lalu ada 2. Jadi seharusnya ada lebih dari 13?

Perhatikan juga bahwa laporan di Pantau untuk pengguna Premium berbeda dengan yg dilaporkan di Laporan Premium per Kabupaten di Layanan. Lihat gambar di bawah untuk contoh Gresik di Pantau

![premium-gresik](https://user-images.githubusercontent.com/249563/214315881-789a95b2-b3cf-4fa2-ad60-00156e15a851.jpg)

**Comment by FirlianiF** [comment]
Doudo - belum premium

**Comment by FirlianiF** [comment]
![lap kab](https://user-images.githubusercontent.com/30171560/215640019-d6f82d46-3332-4518-b170-e10d6bedaa61.PNG)
Sudah diperbaiki dan dicek dengan data pemesanannya dan sudah sesuai

**Comment by FirlianiF** [comment]
untuk pantau harus di cek kembali pada opensid dan paantaunya, karena ada beberapa faktor desa tidak mengirim info ke pantau salah satunya jika desa offline maka tidak akan tterdeteksi di pantau.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan pada PR https://github.com/OpenSID/Layanan_OpenDESA/pull/206
