### ISSUE TITLE
Tampilkan no hp pada list kontak

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#231]
<img width="960" alt="kontaaa" src="https://user-images.githubusercontent.com/30171560/210299430-3eede098-94ff-444a-96c7-9d03121a7251.png">

list kontak sebaiknya ditampilkan nomor hp. Soalnya kalau ada nama yang sama sulit untuk cari kontak yang tepat.
dan mengusulkan key nya adalah nomor HP saja Jadi tidak bisa nomor HP yang sama.

**Comment by devrakapriyo** [comment]
https://github.com/OpenSID/Layanan_OpenDESA/pull/200
