### ISSUE TITLE
pemesanan layanan hapus warna kuning untuk pemesanan yang sudah diperpanjang

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#244]

**Comment by FirlianiF** [comment]
Issue ini dapat dikerjakan jika sudah mengerjakan issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/257

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/234
