### ISSUE TITLE
Perbarui penamaan dan keterangan pada form pasang tema pro

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#248]
True diganti menjadi bawaan tema, False diganti Bawaan OpenSID.
- Judul Kode kota diganti menjadi Pengaturan jadwal sholat
- IP Address diganti Tampilkan Halaman Anjungan
Color dibuat select
-Fluid diganti Tampilkan Halaman Penuh dan Ya Tidak
- menu diganti Tampilkan Menu di Header, Ya Tidak
- Pengaturan Komentar Facebook menjadi judul utama, fbadmin dan fbappid jadi sub judul.
- hilangkan semua keterangan di kanan

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/193
