### ISSUE TITLE
Form pilihan tema disesuaikan untuk konfigurasinya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#251]
Ketika memasang tema ke SiapPakai disesuaikan konfigurasi tema, misalkan untuk tema batuah dan silir hanya pengaturan kode kota untuk mengatur jadwal sholat.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/196
