### ISSUE TITLE
Tambahkan jumlah server dari luar / kabupaten / kota

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#253]
Berkaitan dengan issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/229.

tambahkan field baru kode_kab.
tampilkan jumlah pengguna server luar

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/201
