### ISSUE TITLE
BUG: tidak dapat generate pelanggan baru pada SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#259]
Pada saat pengujian melalui local tidak dapat generate pelanggan baru dan muncul informasi error seperti tangkapan layar berikut:

![Image](https://user-images.githubusercontent.com/68048807/215730469-04748d62-acf0-487e-9264-fa2e365d41cb.JPG)

Setelah dicek sesuai informassi peringatan tersebut domian sudah diarahkan ke alamat IP server:

![Image](https://user-images.githubusercontent.com/68048807/215731114-987322a0-4c9c-4cd7-b016-6407c32238d8.JPG)

Kemungkinan eror tersebut dikarenakan:
1. Perintah exec yang tidak dapat berjalan pada server local
2. terkait jumlah ip pada digit terakhir

Yang perlu dilakukan adalah dilakukan uji coba pada server DevLayanan dan Devsaas untuk memastikan.

**Comment by FirlianiF** [comment]
Sudah di cek pada server layanan, untuk exec dapat berfungsi dengan baik dan tidak ada pengaruh nya dengan jumlah IP pada digit terakhir.

**Comment by FirlianiF** [comment]
Sebelumnya terjadi gagal karena pengecekan di local menggunakan windows, yang mana exec hanya dapat berjalan di sistem operasi linux. solusi nya dapat dicoba jalankan di windows menggunakan docker.

**Comment by scqolbu24** [comment]
@FirlianiF dibuatkan informasi pada panduan
