### ISSUE TITLE
Klik tombol pasang tema tampil whoops

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#265]

**Comment by scqolbu24** [comment]
![error whoops layanan](https://user-images.githubusercontent.com/68048807/218614635-a4b1f76c-af51-4fc6-9b1f-817c1ea8204b.JPG)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/212

![error whoops layanan1](https://user-images.githubusercontent.com/68048807/218615279-2055afff-6dc3-4b99-a1d5-212325187352.JPG)
