### ISSUE TITLE
Upgrade Codeigniter versi 4.3

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#269]
Saat ini Layanan menggunakan Codeigniter versi 4.2 Agar support menggunakan PHP 7.4 dan 8.0 perlu di upgarde ke versi 4.3

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/218

**Comment by vickyrolanda** [comment]
mbak @FirlianiF ini knpa direopen?

**Comment by FirlianiF** [comment]
Ketika di deploy ke server aplikasi menjadi tidak berjalan mas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/289
