### ISSUE TITLE
Mungkinkan penggunaan fitur Premium menggunakan LAN

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#27]
Saat ini fitur Premium tidak bisa dijalankan secara offline menggunakan LAN, karena terbentur teknis penanganan token di Layanan. Diperlukan solusi supaya fitur Premium dapat dijalankan secara offline menggunakan LAN

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, mas @agungsugiarto dr PR ini hanya bisa menambahkan local domain/ip 1 saja. Jika pengguna ingin menambahkan beberapa local domain/ip harus menghubungi pelaksana yg mungkin kedepannya membuat repot.

Saran dari sy mungkin dilayanan cukup ditambahkan input local doman/ip dengan nilai Ya atau Tidak. Sedangkan domain yg membutuhkan akses aplikasi bisa didaftarkan sendiri oleh pengguna di aplikasi OpenSID.

**Comment by roaddee** [comment]
mungkin harus ada entry IP untuk client dan server di OpenSID
jadi harus tentukan IP Server berapa, otomatis yang berada di networknya akan bisa konek, tanpa perlu cek token karena script ada di PC Server

**Comment by andifahruddinakas** [comment]
> mungkin harus ada entry IP untuk client dan server di OpenSID jadi harus tentukan IP Server berapa, otomatis yang berada di networknya akan bisa konek, tanpa perlu cek token karena script ada di PC Server

berarti di layanan cukup sediakan pengecekan local domain Ya atau Tidak. Biar daftar IP Server di tambahkan di aplikasi OpenSIDnya.

**Comment by roaddee** [comment]
iya, dan IP yang dimasukkan itulah yang harus disamakan dengan alamat IP yg sebenarnya digunakan, kalau tidak sama maka premium gk bisa jalan, sedangkan untuk klien harus pada range network, dikunci pada subnet 255.255.255.0
