### ISSUE TITLE
Cek dan perbaiki status langganan menjadi null

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#272]

**Comment by FirlianiF** [comment]
![verifff](https://user-images.githubusercontent.com/30171560/223308080-b403500a-a04b-4b50-accd-d5a806749989.PNG)
desa tsb berhasil mengirim form pendaftaran kerjasama, bisa dilihat di status pelangaannya saat ini menunggu verifikasi email.
dan sudah tidak ada status langganan di db yg null

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/219
