### ISSUE TITLE
Catat dan laporkan penggunaan token premium di domain tidak terdaftar

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#28]
Desa seharusnya menjaga kerahasiaan token layanan masing2. 
Namun ada kecurigaan ada token yg berusaha digunakan oleh yg tidak berhak. Penggunaan seperti itu tidak akan berhasil, karena token dikaitkan dengan domain yg terdaftar di Layanan.

Penggunaan token liar tersebut bisa terjadi karena ada pihak yang berhasil mengakses server desa pelanggan, atau bisa juga karena token tersebut memang sengaja diberikan kepada pihak ketiga.

Khusus untuk layanan premium, diperlukan fitur untuk mencatat dan melaporkan penggunaan token oleh pihak yg tidak berhak. Kemudian, OpenDesa dapat berkonsultasi dengan desa pemilik token liar tersebut, dengan tujuan:

1. meninjau keamanan server mereka yang menyebabkan token bisa diakses oleh pihak lain; atau
2. memberi peringatan bagi desa tersebut jika mereka secara sengaja memberikan kepada pihak lain.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, mohon info spesifik field apa saja yg perlu dicatat untuk disimpan ?

**Comment by eddieridwan** [comment]
- [ ] Kode desa
- [ ] IP address
- [ ] Token
- [ ] Waktu/tgl
- [ ] Browser
- [ ] O/S
- [ ] Domain

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/615
