### ISSUE TITLE
hide/hapus https saat edit domain dan api domain pada pelanggan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#282]
Berdasarkan issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/278, ada permintaan dari pak rudi untuk hide/hapus https saat edit domain dan api domain pada pelanggan

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/229
