### ISSUE TITLE
Tambahkan 38 pelanggan desa baru kota bima

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#283]
- [x] devlayanan update db
- [x] devlayanan update source
- [x] buatkan 38 desa kota bima pelanggan baru
- [x] buatkan 5 pemesanan premium

https://id.wikipedia.org/wiki/Daftar_kecamatan_dan_kelurahan_di_Kota_Bima

**Comment by scqolbu24** [comment]
sudah dikerjakan pada devlayanan
