### ISSUE TITLE
remember me tidak berfungsi

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#292]

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/248

**Comment by scqolbu24** [comment]
issue ini dibuka kembali terkait perubahan jangan di vendor karena ketika composer update akan kehapus

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/Layanan_OpenDESA/pull/252
