### ISSUE TITLE
Sediakan fasilitas copy paste untuk bukti transfer/pembayaran dari pelanggan

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#295]
Saat ini belum ada fasilitas copy paste image /drop images untuk upload entry bukti pembayaran dari pelanggan, 
dengan disediakannya fasilitas ini akan mempercepat proses entry data layanan.
saat ini harus download dulu, nanti baru kemudian upload di layanan pesanan.

Terima kasih

**Comment by apidong** [comment]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/a052dca6-74b6-45a2-8962-d3fa3bc87bfd)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/511
