### ISSUE TITLE
Permudah dalam pencarian nama desa

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#296]
Saat ini cukup merepotkan mencari nama - nama desa yang sangat umum dan hampir sama seperti di Jawa dan Sumatera,
sebaiknya nama desa dicari fix jangan %namadesa%, misalnya nama desa karawang, maka yang dicari atau ditampilkan dalam list adalah yang benar-benar nama desanya hanya karawang jangan karawangi atau akarawang juga ikut. bahkan kecamatan karawang dan kabupaten karawang juga ikut,
atau ebih mudah lagi kalau bisa bertingkat, jadi seperti aplikasi2 lain, pilih provinsi-pilih kabupaten-pilih kecamatan-pilih desa.
terima kasih

**Comment by vickyrolanda** [comment]
Ya saya setuju dibuat bertingkat karena jauh lebih tepat sasaran. lalu setiap select diterapkan plugin select2 agar mudah di cari dan diketik.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/286

namun perlu di ubah lagi sumber data seharusnya mengikuti TrackSID agar jika ada pemekaran kode desa bias mengikuti yang di ubah melalui TrackSID tidak terpisah antara layanan dan TrackSID

**Comment by vickyrolanda** [comment]
sy buka kembali karena ada kesalah pahaman ternyata sebelumnya sudah menggunakan kode desa yg ada di TrackSID tapi ubahan data diambil dari database.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/292
