### ISSUE TITLE
Penyederhanaan Proses

### ISSUE THREAD

**Issue by ihsan2857** [OpenSID/wiki-layanan-opendesa#3]
Di layar pemesan layanan, jika nama pemesan yang dimasukkan tidak ada (belum ada dalam daftar/tabel) maka otomatis menambahkan nama tersebut ke tabel pemesan tanpa harus pindah ke layar edit data pemesan. Tentunya harusnya dengan konfirmasi dulu (untuk memastikan memang nama itu yang dimaksud)

Begitu juga untuk nama dan nomor kontak dan nama pelanggan (nama desa).

**Comment by FirlianiF** [comment]
solusi nya dengan:

-masuk ke halaman pelanggan terlebih dahulu, 
-lalu klik tombol jumlah pemesanan, maka akan masuk ke halaman pemesanan dengan id pelanggan tsb
-klik tombol tambah pemesanan, maka data pelanggan otomatis terpilih dan sudah dipastikan pelanggan tsb sudah terdaftar
