### ISSUE TITLE
Tambahkan kolom untuk menginput tanggal laporan

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-layanan-opendesa#311]
saat ini jika menginput data pesanan di layanan baru tersedia tanggal nota, sedangkan tanggal nota sering dibuat mundur karena permintaan desa sehingga laporan di opendesa tidak sesuai dengan keadaan sebenarnya dan layanan.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/48144047/236364007-6b190535-d4b8-4db8-8390-b20174daa675.png">

tempatkan di tanggal nota

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/249

**Comment by scqolbu24** [comment]
issue dibuka kembali untuk vendor jika di update maka akan kehapus yang telah diubah.
