### ISSUE TITLE
Buatkan laporan layanan sesuai dengan filter

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-layanan-opendesa#312]
saat ini unduh laporan memuat semua jenis layanan. diperlukan laporan layanan sesuai dengan filter. contoh filter tema denatra. ketika di unduh, yang masuk hanya daftar pesanan tema denatra.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/48144047/236364219-e55f73ac-dd6a-415e-87b4-880d85f5ed46.png">

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/257
