### ISSUE TITLE
Gagal input data pelanggan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#318]
Terjadi gagal input data dengan kasus sebagai berikut : 

kasusnya adalah.
desa A kecamatan B pernah ambil layanan dengan domain a.opendesa.id
namun sudah tidak aktif Mei 2022 tahun lalu.

kemudian,
desa A kecamatan X akan ambil layanan dengan domain a.opendesa.id namun gagal karena sudah tertera pernah diinput.

Solusi semetara yang dilakukan adalah menghapus email atas email layanan lama.

**Comment by andifahruddinakas** [comment]
Solusi yang perlu diterapkan adalah tidak mengubah riwayat pelanggan. Buat supaya domain/email yg sdh tidak aktif dapat digunakan ulang. Tanpa mengubah penggunaan domain/email lama tersebut.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/243
