### ISSUE TITLE
Sering terjadi gagal saat melakukan pendaftaran kerjasama (Verifikasi)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#319]
Kasus : 
Terkendala setelah melakukan upload dokumen untuk kerjasama dengan opendesa. setelah saya dapatkan link di email, hasil klik link-nya seperti ini. untuk desa yang mengajukan kerjasa adalah desa Munjul dengan alamat website: munjul.desa.cirebonkab.go.id

Hal serupa pernah terjadi, dengan solusi sementara : 
- [ ] https://github.com/OpenSID/wiki-layanan-opendesa/issues?q=is%3Aissue+pendaftaran+is%3Aclosed+mengecek

Solusi yang diharapkan : 
- agar desa bisa melakukan verifikasi sendiri

**Comment by FirlianiF** [comment]
Duplikat issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/294
