### ISSUE TITLE
Mengecek dan membantu desa desawombokalonggo.com yang tidak dapat melakukan migrasi, token selalu failed.

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#320]

**Comment by FirlianiF** [comment]
Telah dilakukan pengecekan dan solved, kendala ada pada server, sudah dilaporkan pada hosting yang bersangkutan dan kini sudah berjalan normal kembali.

**Comment by eddieridwan** [comment]
@FirlianiF apa kendalanya di server? Apakah ada potensi terjadi pada pengguna lainnya? Apakah dapat terdeteksi secara otomatis? 

Jika iya, sebaiknya ditambahkan pada pemeriksaan kebutuhan sistem pada issue pembuatan wizard instalasi OpenSID.

Jika belum ada cara untuk mendeteksi secara otomatis, maka cara mendeteksi dan mengatasi perlu dimasukkan ke forum.opendesa.id sebagai info bagi pelaksana dan bagi pengguna lainnya. 

Mohon setiap masalah server seperti ini ditangani tuntas seperti dijelaskan di atas.
