### ISSUE TITLE
Data pendaftaran mandiri dari OpenSID membuat data ganda atau error layanan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#324]
Data pendaftaran yang dikirim melalu OpenSID membuat aplikasi error, karena terdapat data kosong.

Pelanggan : 
<img width="751" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/1738ac9e-39b8-4bd8-8381-13090e4c61c3">

Pendaftaran : 
<img width="766" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/386170c5-c0a5-4e58-b0b7-9ee8286acf3c">

Seharusnya : 
Data pelanggan yang belum diverifikasi tidak masuk ke data pelanggan.

**Comment by andifahruddinakas** [comment]
Terkandang pendaftaran yang dilakukan mandiri oleh pengguna melalui OpenSID membuat data jadi duplikasi pada layanan.
<img width="534" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/10f6497a-1863-41fb-bae6-0beb0067a287">

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/247
