### ISSUE TITLE
Perbaiki error saat mengakses data pendaftaran

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#327]
![pendaftaran](https://github.com/OpenSID/wiki-layanan-opendesa/assets/30171560/37917b12-f2d3-4390-945d-443843a8b70f)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/244
