### ISSUE TITLE
Perbaiki halaman login

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#339]
![Halaman Login](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/651f11bd-6e7c-4541-b600-74adf8637141)

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/271

Hasil review:
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/a2143bb2-11ae-4d5c-9ba0-d7d938504e05)
