### ISSUE TITLE
Sesuaikan aturan mengaktifkan pemesanan layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#34]
Dibutuhkan kelonggaran supaya pemesanan layanan, seperti Premium, dapat terus diaktifkan, meskipun pendaftaran Kesepakatan Kerjasama belum rampung.

Alasannya, sering terjadi desa perlu buru-buru mengaktifkan layanan, tetapi Kades mungkin berhalangan untuk menandatangani perjanjian kerjasama.

Untuk menanggapi itu, perubahan proses yg perlu diterapkan adalah sbb:

1. Desa tetap harus memulai proses pendaftaran, minimal sampai verifikasi email, sebelum layanan bisa diaktifkan.
2. Setelah status pendaftaran desa sudah pada tahap email telah diverifikasi, pelaksana dapat membuat dan mengaktifkan layanan yg dipesan, meskipun belum pada tahap perjanjian telah terdaftar.
3. Layanan tersebut akan tetap aktif dalam masa kelonggaran, yaitu 7 hari. Yaitu, setelah 7 hari dan status desa belum juga terdaftar, maka layanan akan terkunci secara otomatis. 
4. Layanan yg terkunci akan diaktifkan lagi secara otomatis, setelah status desa menjadi terdaftar.
5. Sebagai kelonggaran tambahan, juga akan disediakan fitur untuk menambah masa kelonggaran 7 hari lagi. Penambahan masa kelonggaran tambahan tersebut dilakukan pelaksana di aplikasi Layanan, dan dapat digunakan jika dirasa memang diperlukan.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/885 di OpenSID
dan PR https://github.com/OpenSID/Layanan_OpenDESA/pull/50 di Layanan
