### ISSUE TITLE
Perbaiki halaman reset password

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#342]
![2023-07-18_05h55_42](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/0f236cc3-c40a-4451-a11c-b19de6f77721)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/272/files
Hasil review:
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/565f977b-7794-4691-a67b-ccdaa4f15076)
