### ISSUE TITLE
Laporan per jenis layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#35]
Buatkan laporan berisi rincian pelanggan baru per jenis layanan, beserta rangkumannya. Laporan dibuat untuk bulan tertentu.

Untuk bulan tertentu:

- [x] Tampilkan laporan rangkuman jumlah pelanggan baru per jenis layanan termasuk total pembayaran
- [x] Tampilkan laporan rincian pelanggan baru untuk masing2 jenis layanan termasuk jumlah yg dibayar
- [x] Unduh spreadsheet yang berisi dua tab/worksheet:
    - [x] Satu worksheet berisi rangkuman jumlah pelanggan baru per jenis layanan termasuk total pembayaran
    - [x] Satu worksheet berisi rincian pelanggan baru untuk masing2 jenis layanan termasuk jumlah yg dibayar

Detail laporan sebagai berikut:

https://docs.google.com/spreadsheets/d/1VMtrTnipxTYGqlO_ee6TYjUaTj35TVri33nO0rbSN4Y/edit?usp=sharing

### Rangkuman

![image](https://user-images.githubusercontent.com/249563/144841579-458acda7-e505-4bf7-9643-ad16eb17138a.png)

### Rincian

![image](https://user-images.githubusercontent.com/249563/144841263-2461c9cc-8c3f-45a2-8eb8-6a0e5729504a.png)

### Catatan

Pada penerapannya, di spreadsheet di atas, kolom Layanan dan Sub-Layanan bisa diulang pada setiap baris, jika akan memudahkan.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan karena di layanan tidak diterapkan sub-layanan / kategori, jadi tidak bisa untuk ditampilkan pak. Akan banyak merombak jika diterapkan.

Apakah seperti ini saja yg nanti dijadikan laporan pemesanan layanan?
<img width="683" alt="image" src="https://user-images.githubusercontent.com/10989147/144950024-54e535dd-e9c4-41db-ad60-d02dc39dddb5.png">

**Comment by ariandii** [comment]
usul tambahan pak,

tersedia kolom revisi beserta kolom keterangan, penerimaan maupun pembayaran, untuk saat ini kadang terjadi di invoice tertera 1.400.000 sedangkan yg diterima sesuai struk 1.350.000

dan juga kadang di invoice ada kesalahan input jenis layanan.

Atau mungkin ada alternatif lain.

**Comment by agungsugiarto** [comment]
- Kategori layanan: https://github.com/OpenSID/Layanan_OpenDESA/pull/33
