### ISSUE TITLE
Tambah perkiraan penerimaan bersih di menu Laporan > Laporan Layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#350]
Tambahkan info di Laporan > Laporan Layanan supaya bisa secara cepat melihat perkiraan dana yg diterima pada periode yg dipilih.

Perkiraan bersih perlu dimasukkan dengan info dari pelaksana layanan dan dari Divisi Komersial. Dihitung dengan mengurangi biaya produksi dan biaya honor pelaksana. 

Sebagai contoh:

1. Layanan Premium dikurangi honor bagi pelaksana untuk memasukkan entri ke aplikasi Layanan 
2. Biaya Tambahan penerimaan bersih nol, karena merupakan biaya ongkos pengiriman anjungan yg dikeluarkan 
3. Hosting dikurangi perkiraan biaya bagi IDCH/Alibaba untuk satu tahun bagi masing2 konfigurasi
4. dstnya..

<img width="1356" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/139be85c-140c-4120-bec2-018c63e24992">

**Comment by agungsugiarto** [comment]
mas @vickyrolanda perlu informasi lebih detail terkait masing2 kategori layanan rumus perhitungannya seperti apa!

**Comment by apidong** [comment]
> mas @vickyrolanda perlu informasi lebih detail terkait masing2 kategori layanan rumus perhitungannya seperti apa!

sebenarnya kalau pengen enak, dibuatkan rumus di master layanan. rumus penambahan dan pengurannya berdasarkan kode rekening

**Comment by agungsugiarto** [comment]
@apidong seperti apa gambaran perhitungannya mas?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/550
