### ISSUE TITLE
kalau sudah ada bukti pembayaran, dan ubah status pembayaran dari belum lunas ke lunas, maka bukti tidak wajib diinput

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#357]

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/283

Hasil Review:
1. Testing 1
    a. Dilakukan Tambah Pemesanan Baru dengan status belum lunas dan tambahkan bukti pembayaran kemudian simpan
    b. Pemesanan diubah dengan status lunas kemudian simpan
2. Testing 2
    a. Dilakukan Tambah Pemesanan Baru dengan status belum lunas kemudian simpan  
    b. Pemesanan diubah dengan status lunas dan tambahkan bukti pembayaran kemudian simpan
4. Testing 3
    a. Dilakukan Tambah Pemesanan Baru dengan status belum lunas kemudian simpan  
    b. Pemesanan diubah menambahkan bukti pembayaran kemudian simpan (status massih belum lunas)
    c. Pemesanan diubah dengan status lunas kemudian simpan.
