### ISSUE TITLE
ubah penamaan hasil data filter pelanggan

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#360]
ubah penamaan di panah merah bawah menjadi data / data pelanggan agar lebih jelas dan tidak membingungkan.

![257672396-5015584f-752d-482c-a9f9-d1c111165d761](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/5573d06b-4b8e-42df-8de6-bc862d7274c4)

**Comment by eddieridwan** [comment]
@habibie11 Jika ini terkait pembahasan penerapan issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/360, harap ditunggu sampai sudah dilakukan review dan analisis ulang, bersama @vickyrolanda

**Comment by habibie11** [comment]
> @habibie11 Jika ini terkait pembahasan penerapan issue #360, harap ditunggu sampai sudah dilakukan review dan analisis ulang, bersama @vickyrolanda

baik pak

**Comment by habibie11** [comment]
issue ini akan diterapkan atau tidak mas @vickyrolanda ?

**Comment by vickyrolanda** [comment]
Saat ini issue tidak perlu diterapkan , 
seperti contoh berikut ini yang membedakan dalam penerapan data & entri : 
Jika Anda memiliki data berupa nama, alamat, nomor telepon, dan alamat email seseorang, maka masing-masing dari ini adalah data. Namun, ketika Anda mengumpulkan semua data ini dan membuat catatan pribadi yang mencakup semua informasi ini, itu disebut sebagai entri. Entri adalah cara mengorganisasi dan menyusun data menjadi suatu kesatuan yang bermakna.

jadi ilustrasi diatas mewakili bahwa jumlah itu adalah perwakilan dari jumlah data yang dikumpul yang biasa disebut dengan entri. sehingga penerapan tulisan entri sudah tepat dibanding menggunakan data.
