### ISSUE TITLE
bug: versi yang terpasang di layanan tidak sesuai dengan versi yang dipasang di web desa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#361]
Informasi versi terpasang di layanan.
![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/5e5a24e7-89d3-40d7-97e1-916e8a28828e)

Informasi versi terpasang di Web
![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/d2bda5c1-391a-4c9a-a08b-c7ae8c1c5edf)

Informasi terpasang di dasbor SiapPakai
![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/64eca0f3-d914-4c0a-ae55-a9ee9398cf3d)

Informasi di Pantau
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/12c543df-4791-4f3d-b30e-6c9bccfaf0b1)

Seharusnya informasi tersebut sama semua.

berkaitan dengan issue https://github.com/OpenSID/wiki-saas/issues/300

**Comment by habibie11** [comment]
Sudah di cek, saya tidak menemukan adanya error, setiap membuat pesanan siappakai aplikasi selalu mengambil tanggal terakhir dari pesanan premium dan otomatis dari siappakai akan mengambil versi terbaru dari git. boleh direview dan didiskusikan kembali terkait issue ini.
cc @vickyrolanda @FirlianiF @scqolbu24 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/1828ab37-96ba-4cfc-b9a1-c857b2e33302)

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/db20d3c5-db71-44cc-9c4e-5c8ae7023c6e)

**Comment by vickyrolanda** [comment]
saya close karena issue sudah tidak relevan dan sudah di sesuai dengan keadaan saat ini.
