### ISSUE TITLE
Bug : Tidak bisa simpan token

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#363]
Ketika simpan token muncul error seperti foto dibawah ini

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/37b09f82-a858-4913-81b2-7a2c455c93d7)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/302
