### ISSUE TITLE
cek sumber data kode desa

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#364]
jika dilihat dari sumber desa yang ada di layanan, desa yg di input itu berdasarkan desa yang di tambah melalui menu pelanggan.
namun data desa diambil melalui database layanan, data ini akan menjadi rancu jika ada pemekaran kode desa antara TrackSID & layanan karena untuk OpenSID & mobile kode desa di ambil melalui TrackSID. 

Perubahan yang perlu di lakukan : 

- [ ] Cek bagian yang menggunakan kode desa pada layanan
- [ ] Cek perubahan jika sumber di ambil melalui TrackSID (cek relasi antar table) 
- [ ] Ubah Penggunakan kode desa melalui database layanan di ubah ke TrackSID

**Comment by habibie11** [comment]
ketika input dan edit data pelanggan desa sudah mengambil kode desa dari TrackSID dan data pelanggan dengan kode desa itu disimpan ke database layanan.
cc mas @vickyrolanda
issue yang terkait :
https://github.com/OpenSID/wiki-layanan-opendesa/issues/296
https://github.com/OpenSID/wiki-layanan-opendesa/issues/235

**Comment by vickyrolanda** [comment]
> ketika input dan edit data pelanggan desa sudah mengambil kode desa dari TrackSID dan data pelanggan dengan kode desa itu disimpan ke database layanan. cc mas @vickyrolanda issue yang terkait : #296 #235

makasih mas sarwono, issue ini sy close karena tidak ada pr sesuai penjelasan dan diskusi maka tidak perlu ada ubahan pada sumber kode desa tetap melalui trcksid
