### ISSUE TITLE
Bug : Pelanggan yang baru ditambahkan tidak masuk/tampil di tabel

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#365]
error ini terjadi ketika menambahkan pelanggan baru dengan domain yang pernah dipakai di pelanggan lain.
1. buat pelanggan baru
2. pilih desa yang belum pernah dibuat ( misal : desa sidumulyo kecamatan sekampung)
3. isi domain yang sudah pernah dibuat ( misal : pasirampo.opendesa.id)
4. setelah simpan, muncul notif berhasil, tapi data tidak masuk.

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/8e280001-3281-43d4-949e-5d387f84c5a4)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/291
