### ISSUE TITLE
Sesuaikan ikon foto ketika edit/tambah pemesanan

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#366]
Ketika edit foto sesuaikan ikon foto sesuai dengan kondisi jika belum upload atau sudah upload agar bisa mengetahui apakah sudah upload atau belum

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/8c7ce943-ecf4-4d3b-8cd4-34da4e5dca53)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/290
