### ISSUE TITLE
Sesuaikan jenis inputan pada menu pelanggan bagian jenis pelanggan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#368]
Kondisi saat ini ketika tambah pelanggan lalu pilih jenis pelanggan "kecamatan" maka yang akan muncul ada lah daftar desa, lalu ketika di simpan yang di ambil adalah kecamatan.

maka proses di atas perlu di sesuaikan dengan opsi pilihan bertahap juga, namun hanya sampai tahap kecamatan saja.

Ubahan yang diperlukan : 
1. Sesuaikan select bertahap Provinsi , Kabupaten & Kecamatan.
2. Cek data pelanggan yang sudah terselect sebelumnya apakah ada tertrigger pada perubahan.
3. Jika ter trigger maka dibutuhkan ubahan migrasi agar dapat membuat data menjadi lebih konsisten

**Comment by habibie11** [comment]
data pelanggan desa yang sudah diselect sebelumnya tidak bermasalah ketika menambah pelanggan jenis kecamatan
cc mas @vickyrolanda 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/68f07734-33de-4ec5-954d-2e74ee9b521f)

**Comment by vickyrolanda** [comment]
mas @habibie11 : 
juga perlu disesuaikan untuk edit yang untuk kecamatan mas, 
sama seperti jenis pelanggan desa. 

saat ini edit  jenis kecamatan :
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/65b6e1ea-63d8-412d-acd0-729d1fbbfed9)

kalo edit di desa seperti ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/eae936d2-caf4-4d0d-9850-34beb59feabf)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/297
