### ISSUE TITLE
Laporan pelanggan premium per kabupaten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#37]
Bagi setiap kabupaten yg pelanggan premium aktifnya telah mencapai 100 desa, OpenDesa akan merekrut programmer yg dikhususkan membantu Diskominfo kabupaten ybs untuk menerapkan perbaikan/penambahan fitur OpenSID/OpenDK yg diprioritaskan kabupaten ybs. 

Untuk memudahkan memantau status kabupaten, diperlukan laporan sbb:

- [x] daftar kabupaten denngan data jumlah pelanggan Premium aktif
- [x] diurut dengan jumlah pelanggan terbanyak di atas
- [x] laporan juga menampilkan jumlah pelanggan Premium baru pada bulan berjalan dan bulan sebelumnya (untuk memberi indikasi laju penambahan pelanggan Premium)

**Comment by agungsugiarto** [comment]
Sebenarnya sudah bisa diterapkan di pelanggan pak, karena sekarang bisa di filter per kabupaten dan layanannya.

**Comment by eddieridwan** [comment]
Diperlukan laporan langsung bisa lihat semua kabupaten sekaligus khusus untuk premium.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan yg ditampilkan seperti ini?

| Kabupaten | Jumlah Pelanggan Premium |
|-----------|--------------------------|
| Kediri    | 20                       |
| Gresik    | 10                       |

**Comment by eddieridwan** [comment]
Tambah kolom provinsi, dan penambahan jumlah premium dalam bulan ini dan bukan sebelumnya.
