### ISSUE TITLE
Tambah filter "aktif" bagi daftar pelanggan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#370]
Dibutuhkan laporan pelanggan aktif, misalnya "semua pelanggan OpenSID Premium yg masih langganannya masih aktif". Saat ini ada pilihan "Semua", tetapi itu menampilkan juga pelanggan yg sudah habis masa langgannya. Sedangkan filter yg lain adalah untuk status lebih spesifik (bukan yg aktif saja). 

<img width="1212" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/3279727e-d1de-44ec-8e44-127719f40018">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/298
