### ISSUE TITLE
Laporan > Laporan Premium jangan tampilkan kabupaten yg tidak ada pelanggan premium aktif

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#372]
<img width="1401" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/5d962497-a922-4a23-b520-466789bf5e06">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/300
