### ISSUE TITLE
Bug : Hasil export laporan pemesanan berbeda

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#375]
Berdasarkan pertemuan dengan pelaksana pada hari rabu (30/08/23), terdapat bug modul laporan layanan yaitu jumlah hasil export data dari laporan layanan memiliki perbedaan dengan total jumlah pemesanan.
misalnya di jumlah pemesanan pada kategori layanan premium adalah 114.
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/d4c869c8-7000-43e1-905e-d40a2024ad76)

namun di hasil export jumlahnya ada 115.
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/3d8d93f1-d3b3-4aa1-ae99-51ecfdfb92b4)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/308
