### ISSUE TITLE
Bug/error: Rincian Pemesanan Premium ketika perpanjangan tidak menampilkan invoice sebenarnya

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/wiki-layanan-opendesa#376]
### Jelaskan error yg dialami

Rincian Pemesanan Premium ketika perpanjangan tidak menampilkan invoice sebenarnya

### Cara untuk mereplikasi errornya

1. layanan pelanggan
2. perpanjangan premium

### Hasil yg diharapkan

Rincian Pemesanan Premium ketika perpanjangan menampilkan invoice sebenarnya

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/af6ec1db-8c6c-4e3e-9555-a3392f20ab1a

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.0

### Tema Yang Digunakan

esensi

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, terkait layanan saya pindahkan ke repo layanan. Pada halaman OpenSID hanya menampilkan saja, yang memproses ada pada bagian layanan.

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, setelah di cek dilayanan, invoice sebagai berikut : 
<img width="506" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/6be84843-37e1-4cb8-8777-6ec79cb9c7e9">

adapun jika ada perubahan yang ingin dilakukan saat perpanjangan bisa melalui pelaksana, karena perpanjangan pada OpenSID berdasarkan langganan terakhir (belu bisa memilih yg akan diperpanjang).

**Comment by mah-mudi** [comment]
Ok mas

**Comment by vickyrolanda** [comment]
mas @habibie11 untuk masalah ini juga bisa berikan opsi pada OpenSID, ketika klik perpanjng layanan maka ada opsi pilihan layanan mana saja yang ingin di perpanjang sehingga untuk generate invoice akan tergenerate berdasarkan layanan yang di pilih untuk di perpanjang saja. 

saat ini opsi itu tidak tersedia masih hanya mengikuti layanan yang terakhir.

mas @habibie11 bisa terapkan pada OpenSID dan disesuaikan dengan API yang ada pada layanan.

**Comment by habibie11** [comment]
mas @vickyrolanda untuk penerapan di OpenSID perlu didiskusikan kembali dengan mas @andifahruddinakas

**Comment by vickyrolanda** [comment]
mas @habibie11 issue ini juga bisa sebagai penambahan atau penyesuaian dari sisi generate invice yang parameternya diterima melalui OpenSID  di issue ini : https://github.com/OpenSID/OpenSID/issues/7190

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/319
