### ISSUE TITLE
Ubah tipe input harga dari text ke number

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#378]
Di modul pemesanan->edit pemesanan
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/8d43cc38-c35e-413c-896d-67da61ae21f3)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/307
