### ISSUE TITLE
pemesanan lama masih ikut ke pelanggan itu dengan nama PPN

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#379]
hasil dari diskusi dengan mas akas dan mba firli (06/08/2023) terkait anjungan, diketahui ketika membuat pemesanan dengan kategori PPN, anjungan masih mengikuti PPN sehingga pelanggan bisa menggunakan fitur anjungan di openSID.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/303
