### ISSUE TITLE
ketika memperpanjang pemesanan setelah simpan data pemesanan menjadi dua

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#380]
saat ini setelah melakukan perpanjangan pemesanan, data pemesanan yang berhasil diupdate ada 2 pemesanan yaitu pemesanan sebelumnya dan perpanjangnya, sehingga membuat bingung user ketika melakukan perpanjang pemesanan. bisa disesuaikan cukup satu pemesanan perpanjangan saja yang berhasil diupdate sehingga yang berhasil diupdate hanya pemesanan perpanjangan.

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/0c6583d0-de00-4729-b3d8-9422900f34f2)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/305
