### ISSUE TITLE
validasi generate token hanya ketika pemesanan lunas

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#381]
saat ini ketika membuat pemesanan dengan status yang belum lunas token sudah tergenerate, bisa dibuatkan token tergenerate hanya ketika pemesanan itu sudah lunas.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/306
