### ISSUE TITLE
generate token ketika pemesanan dihapus

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#382]
saat ini ketika menghapus pemesanan token tidak tergenerate ulang sehingga membuat pelanggan masih memiliki layanan sebelumnya, untuk mengatasi ini bisa lakukan generate token ketika pemesanan yang statusnya sudah lunas dihapus.

**Comment by vickyrolanda** [comment]
mas untuk issue ini, bukannya ketika pesanan di hapus pelanggan tetap perlu perbarui di layanan pelanggan dan pesanan terupdate yang akan tampil ? 

karena jika token di generate ulng menjadi report karna pengguna perlu input ulang token kan.

**Comment by vickyrolanda** [comment]
saat ini issue ini saya close karna untuk perbarui token masih belum relevan untuk digunakan pada OpenSID .
karena jika token di generate ulng menjadi report karna pengguna perlu input ulang token kan.
