### ISSUE TITLE
Terdapat kerentanan pada fitur upload

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#383]
Terdapat kerentanan pada fitur upload, hal ini diindikasikan dengan ditemukannya file berekstensi .php dalam folder bukti dan ttd sebagaimana dijelaskan lebih lanjut pada laporan serangan siber https://github.com/OpenSID/wiki-keamanan/issues/34

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/311
