### ISSUE TITLE
gagal akses modul laporan premium

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#387]
<img width="960" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/ac545a83-69b0-4c2c-abf9-9b3f8eca519d">

**Comment by habibie11** [comment]
sudah diperbaiki di server
https://trello.com/c/11dTOkyP/45-tidak-bisa-akses-table-view-di-layanan

cc mas @andifahruddinakas @vickyrolanda
