### ISSUE TITLE
Penyesuaian tema pro siappakai

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-layanan-opendesa#391]
saat ini ketika membuat tema pro dari layanan nama tema masih menggunakan nama default  dari tema nya dan perlu dilakukan penyesuaian dengan merubah jenis hurufnya menjadi kecil.

issue terkait : https://github.com/OpenSID/wiki-saas/issues/318

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/318
