### ISSUE TITLE
Penyesuaian konfigurasi dengan server vps

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#394]
Muncul error ini terjadi setelah pemindahan lokasi server dari sebelumnya cpanel ke vps, kemungkinan perlu ada penyesuaian dengan server vps karna sebelumnya aman.

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/7101bbe2-901e-4bf9-a0a2-bb655a07f469)

saat ini solusi sementara yang digunakan adalah dengan mendisable kondisi di kode berikut. dan butuh penyesuaian dengan server vps.

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/47f8a78c-8345-4331-a364-89640d8c6175)

**Comment by habibie11** [comment]
setelah dicek menampilkan ip yang dituju ke siappakai dari masing-masing domain sehingga untuk issue ini sementara diaktifkan kembali untuk kondisi pengecekan IP jika ada pelanggan pendaftar kembali mengalami error maka issue ini akan ditindak lanjuti.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/325
