### ISSUE TITLE
Bug : perbaiki email verifikasi pelanggan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#397]
isi email yang diterima hanya seperti digambar ini

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/196d56da-0c31-4bd0-a431-1b5fdfdeef46)

**Comment by habibie11** [comment]
cek / replikasi dari opensid
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/2b21dd1f-eb3c-47df-9fff-3939cd3a1a2d)

**Comment by vickyrolanda** [comment]
issue di close karna tidak ter replikasi
