### ISSUE TITLE
Penamaan Kategori Dasbor Saas statis di OpenSID

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#398]
Saat ini:
![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/d49f4636-5e40-4941-9f82-c2e38037360c)

Perlu ditambahkan data berikut : 

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/6f7a5f10-010c-4fbb-a910-bd7d69295c04)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/455
