### ISSUE TITLE
Sediakan Tombol Perpanjangan Otomatis

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#4]
Saat ini ketika ada perpanjangan layanan, harus membuat lagi pemesanan layanan, yang menurut kami pelaksana kurang efisien.

Yang diharapkan : 
Sediakan tombol untuk melakukan perpanjangan, sehingga cukup mempermudah.

**Comment by andifahruddinakas** [comment]
pak @roaddee, tombol yg akan dibuat ini hanya untuk perpanjangan layanan yg sama. jika perpanjangan dengan penambahan/penguran layanan mungkin bisa di buat ulang. Apa betul seperti itu???

**Comment by roaddee** [comment]
betul, yang benar2 sama.
kalau ada penambahan atau pengurangan layanan, maka terbitkan invoice baru saja

**Comment by eddieridwan** [comment]
@afa28 Baik perpanjangan maupun perubahan **harus** dibuatkan pemesanan baru, termasuk penerbitan faktur baru. Jadi **jangan** mengubah pemesanan yg sudah lunas. Setelah lunas, pemesanan **tidak** boleh diubah.

Jadi tombol perpanjangan bisa saja disediakan untuk memudahkan. Tapi yg dilakukan tombol tersebut adalah membuat pemesanan baru dengan data yg sama.

Ini perlu untuk menjaga keutuhan/keabsahan pelaporan keuangan/pemesanan kita ke depan. Kita harus selalu bisa menerbitkan **setiap** faktur yg telah dibuat sebelumnya.

**Comment by andifahruddinakas** [comment]
> @afa28 Baik perpanjangan maupun perubahan **harus** dibuatkan pemesanan baru, termasuk penerbitan faktur baru. Jadi **jangan** mengubah pemesanan yg sudah lunas. Setelah lunas, pemesanan **tidak** boleh diubah.
> 
> Jadi tombol perpanjangan bisa saja disediakan untuk memudahkan. Tapi yg dilakukan tombol tersebut adalah membuat pemesanan baru dengan data yg sama.
> 
> Ini perlu untuk menjaga keutuhan/keabsahan pelaporan keuangan/pemesanan kita ke depan. Kita harus selalu bisa menerbitkan **setiap** faktur yg telah dibuat sebelumnya.

pak @eddieridwan, pak @roaddee, jika tekan tombol perpanjangan apakah langsung diperpanjang (menambah pemesanan baru) sesuai kondisi di atas dengan bukti pembanyaran kosong. atau tampilkan modal untuk upload bukti pembayaran sebelum melanjutkan, baru kemudian disimpan???

**Comment by roaddee** [comment]
biar satu jalan, maka lebih baik pakai modal, jika modal ditutup dalam kondisi tidak upload bukti maka batal.

**Comment by agungsugiarto** [comment]
Sudah di gabung ke development melaui pr https://github.com/OpenSID/Layanan_OpenDESA/pull/8
