### ISSUE TITLE
Pelanggan Kecamatan

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#40]
Mohon ditambahkan Kecamatan sebagai Pelanggan, meski sedikit ada juga Kecamatan yang menjadi Pelanggan terkait penggunaan OpenDK di Wilayahnya

**Comment by eddieridwan** [comment]
Issue ini untuk kecamatan yg berlangganan hosting di OpenDesa. Saat ini pelanggan Layanan harus desa, sedangkan untuk OpenDK pelanggan adalah kecamatan. Jadi juga perlu dimungkinkan kecamatan menjadi pelanggan di aplikasi Layanan. Hal2 lain, seperti perlunya ada kontak tidak berubah. Tetapi perjanjian kerjasama perlu disesuaikan supaya bekerjasama dengan pemerintah kecamatan, bukan desa.

**Comment by eddieridwan** [comment]
@apidong mohon buatkan issue OpenDK untuk ditambahkannya notifikasi status layanan di OpenDK. Dan juga issue untuk pembuatan kerjasama, seperti halnya di OpenSID.

**Comment by apidong** [comment]
@eddieridwan baik pak

**Comment by roaddee** [comment]
Ditutup saja issue ini. Tidak urgent.
Biar kecamatan hosting di kominfo mereka masing-masing saja. Toh hanya beberapa saja.

**Comment by eddieridwan** [comment]
@FirlianiF biarkan tidak ditutup. Karena ke depan kita akan menggalakkan penggunaan OpenDK.

**Comment by FirlianiF** [comment]
- [ ] Data Pelanggan Kecamatan
- [ ] Buat Pemesanan untuk Pelanggan Kecamatan
- [ ] Sinkronisasi dengan OpenDK

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/130
