### ISSUE TITLE
Data tema yang tampil pada Dasbor SiapPakai tidak sesuai dengan tema pada data pemesanan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#402]
Contohnya pada desa tersebut, ketika dicek hanya memesan tema pusako dan batuah. seharusnya pada pilihan tersebut tidak ditampilkan tema denatra,denava, dan silir.
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/30171560/796b4d78-c64a-4c63-95bf-b9eab04fb3e0)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/328
