### ISSUE TITLE
Data jenis layanan yg masuk ke faktur harus mati

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#41]
Saat ini data jenis layanan, seperti harga, dimasukkan ke faktur secara dinamis. Ini bukan cara pencatatan yg aman. Seharusnya harga yg digunakan di faktur bersifat mati dan tidak berubah jika harga jenis layanan berubah. Sebagai contoh, jika harga VPS 7GB berubah dari 1.350.000 menjadi 1.400.000, maka faktur sebelumnya yg berisi harga lama `TIDAK` berubah.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/Layanan_OpenDESA/pull/30
