### ISSUE TITLE
CRUD Pelanggan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#412]
Issue ini dikerjain dalam CRUD : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/4ce69980-eda2-4244-9f3a-d228a0197f34)

- [ ] Daftar Pelanggan sudah di kerjain pada PR https://github.com/OpenSID/Layanan_OpenDESA/pull/371
- [ ] Tambah Pelanggan
- [ ] Hapus Pelanggan
- [ ] Edit Pelanggan
- [ ] Daftarkan menu ke dalam database melalui migrasi , referensi bisa lihat PR Ini https://github.com/OpenSID/Layanan_OpenDESA/pull/371

**Comment by vickyrolanda** [comment]
mas @habibie11  bisa lihat PR ini https://github.com/OpenSID/Layanan_OpenDESA/pull/368/ karna berkaitan dengan issue ini sekalian lihat teknisnya apakah di PR tersebut perlu penyesuaian lagi agar di kabari ke mbak firly.

**Comment by vickyrolanda** [comment]
mas @habibie11 untuk isseu ini batasi pengerjaannya sesuai deskripsi yaitu , 

- [ ]  Tambah Pelanggan
- [ ] Update Pelanggan 
- [ ] Lihat Detials Pelanggan
- [ ] Daftarkan menu ke dalam database melalui migrasi , referensi bisa lihat PR Ini https://github.com/OpenSID/Layanan_OpenDESA/pull/371

untuk daftar pelanggan sudah di kerjain pada PR ini https://github.com/OpenSID/Layanan_OpenDESA/pull/371

**Comment by habibie11** [comment]
> mas @habibie11 bisa lihat PR ini [OpenSID/Layanan_OpenDESA#368](https://github.com/OpenSID/Layanan_OpenDESA/pull/368) karna berkaitan dengan issue ini sekalian lihat teknisnya apakah di PR tersebut perlu penyesuaian lagi agar di kabari ke mbak firly.

mungkin bisa ditambahkan informasi server di detail pemesanan, sama seperti di detail pelanggan berikut, cc mbakl @firliani : 
<img width="687" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/56639378/a3d82a4c-cb1c-4a96-9784-8eb660fcee3d">

**Comment by FirlianiF** [comment]
> > mas @habibie11 bisa lihat PR ini [OpenSID/Layanan_OpenDESA#368](https://github.com/OpenSID/Layanan_OpenDESA/pull/368) karna berkaitan dengan issue ini sekalian lihat teknisnya apakah di PR tersebut perlu penyesuaian lagi agar di kabari ke mbak firly.
> 
> mungkin bisa ditambahkan informasi server di detail pemesanan, sama seperti di detail pelanggan berikut, cc mbakl @Firliani : <img alt="image" width="687" src="https://private-user-images.githubusercontent.com/56639378/300325009-a3d82a4c-cb1c-4a96-9784-8eb660fcee3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDA1MjIsIm5iZiI6MTcwNjUwMDIyMiwicGF0aCI6Ii81NjYzOTM3OC8zMDAzMjUwMDktYTNkODJhNGMtY2IxYy00YTk2LTk3ODQtOGViNjYwZmNlZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMThlNWFmYTFhYWIxNWNlODIxZjUxNDE3OGJiZTFlYTIxMzM4MWZkMTAyYjUyYTQ0ZDgwNmY2MzAwNmU5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d7DORa4dOctu2MoOu0v2DddnCzFfazALCQM3TrqoJu0">

kalau saya pas awal buat pr sudah ambil dari branch mas afila, dan sudah merge dari layanan-laravel juga.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/377
