### ISSUE TITLE
Notifikasi Pesanan Baru & Pesanan Akan berakhir

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#415]
![image](https://github.com/user-attachments/assets/f051f492-e0d6-4672-8ef0-a653b2c8369f)

mohon periksa apakah norifikasi pemesanan baru & pesanan akan berakhir sudah ditambahkan pada informasi yang ada di lonceng. 

saat ini juga perlu di cek karena saat klik semua notifikasi tampilannya terlihat blank putih seperti dibawah ini : 
![image](https://github.com/user-attachments/assets/3d998485-4059-4f34-becb-b8c3c8434291)

**Comment by FirlianiF** [comment]
Pesanan akan berakhir sudah ada di notifikasi, halaman detail notifikasi nya tampil.
Jadi yang harus ditambahkan yaitu data notifikasi pesanan baru.

![image](https://github.com/user-attachments/assets/aa66dd8c-8269-4af6-993b-a7e1fee4e1c4)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/672
