### ISSUE TITLE
CRUD Layanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#418]
Layanan ini berkaitan dengan : issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/417 sebelum kerjain ini maka pastikan modul jenis layanan telah selesai, karena pada proses pembuatan fitur ini jenis layanan digunakan sebagai kategori jenis layanan. 

untuk pembuatan table bisa menggunakan seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/3981bf54-04f7-4413-8d09-ad79baf34271)

Batasan pengerjaan : 
1. Buatlah tambah data sesuai dengan input system lama 
2. lalu kaitkan jenis layanan saat ingin menambah layanan baru
3. lalu buat fungsi update pada data layanan yang berhasil di tambah
4. lalu buat juga fungsi hapus pada layanan yang berhasil ditambah
5. Tampilkan layanan seperti berikut ini : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/d5a62246-1c5e-4a74-862a-3bca8907c413)

**Comment by agungsugiarto** [comment]
mas @vickyrolanda issue ini cukup besar, ini berapa poin sebelumnya?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/331
