### ISSUE TITLE
Pisahkan laporan ke submenu masing2 dan perbaiki Laporan Kabupaten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#42]
Saat ini filter, urut dan cari Laporan Kabupaten tidak berfungsi baik. Juga kurang enak navigasi laporan yg ditumpuk. 

![image](https://user-images.githubusercontent.com/249563/147919710-ace6e82d-15c9-417c-aa72-10d3782f8c15.png)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/Layanan_OpenDESA/pull/32
