### ISSUE TITLE
Modul Server SiapPakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#432]
- [x] create server siappakai
- [x] tampilkan data  server siappakai
- [x] ubah data server siappakai
- [x] tampilkan jumlah pengguna dasbor siappakai yang menggunakan server tersebut
- [x] kirim API ke OpenSID SiapPakai
- [x] Penambahan Helpers untuk format_domain.
- [x] Penambahan Helpers untuk format_api_domain.
- [x] sesuaikan icon sesuai form
- [x] Penambahan validasi js untuk kode kab berdasarkan jenis server yang dipilih.
- [x] penambahan konversi tanggal dari api ditampilkan dengan format datetime di halaman daftar server.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/342
