### ISSUE TITLE
Laporan Bulanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#438]
Tambahkan laporan bulanan yang akan digunakan divisi sekretariat sebagai laporan keuangannya : 
Keterangan *
Saldo Awal	= Diamabil dari total pendapatan - pengeluaran dibulan sebelumnya
Pendapatan	= Total Pendapatan Bulan saat ini
Pengeluaran	= Total Pengeluaran Bulan saat ini
Saldo Akhir	= Total dari (Saldo Awal + Pendapatan Bulan saat ini ) - Pengeluaran Bulan Saat Ini

Format laporan terlampir di excel berikut ini : 
[FORMAT LAPORAN BULANAN.xlsx](https://github.com/user-attachments/files/15963339/FORMAT.LAPORAN.BULANAN.xlsx)

**Comment by pandigresik** [comment]
> Tambahkan laporan bulanan yang akan digunakan divisi sekretariat sebagai laporan keuangannya : Keterangan * Saldo Awal = Diamabil dari total pendapatan - pengeluaran dibulan sebelumnya Pendapatan = Total Pendapatan Bulan saat ini Pengeluaran = Total Pengeluaran Bulan saat ini Saldo Akhir = Total dari (Saldo Awal + Pendapatan Bulan saat ini ) - Pengeluaran Bulan Saat Ini
> 
> Format laporan terlampir di excel berikut ini : [FORMAT LAPORAN BULANAN.xlsx](https://github.com/user-attachments/files/15963339/FORMAT.LAPORAN.BULANAN.xlsx)

total pendapatan sumber datanya darimana ?
total pengeluaran sumber datanya darimana ?

**Comment by pandigresik** [comment]
Apakah ada mekanisme closing / tutup buku bulanan ?

**Comment by pandigresik** [comment]
mas @vickyrolanda bisa cek di telegram https://t.me/c/1890895110/9432

**Comment by vickyrolanda** [comment]
Laporan Bulan terbagi menjadi 3 bagian  : 

1. Ringkasan 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/c093fe0e-8490-4d77-89d2-4b11e17ec0b7)

Pengeluaran = total pengeluaran diambil dari tabel "transaksi" melalu kolom  "outflow" berdasarkan "tgl_transaksi"
Pendapatan = total pemesanan dengan status_pembayaran = 1 dan direlasikan dengan tabel pemesanan_layanan untuk mendapat total pendapatan.


3. Pendapatan
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/a9b059b7-4073-4fd7-83a5-46bb3de05892)

- untuk pendapatan dapat diambil berdasarkan tabel "pemesanan" dengan "status_pembayaran = 1 " sehingga tidak perlu menentukan berapa yang dibayar berdasarkan pembayaran termin namun jika dalam pemesanan status_pembayaran = 1 maka semua pemesanan pada tabel "pemesanan_layanan" telah dibayar lunas. 

maka tinggal menyusun tampilan laporan berdasarkan kode rekening, pertama lihat kode rekening yang dikaitkan berdasrkan tabel layanan pada kolom " kode_rekening" namun tabel tersebut disusun berdaskan tabel kode_rek1 kategori pengeluaran lalu looping sampai dengan kode_rek4 maka kode_rek4 yang dapat dikaitkan pada tabel layanan di kolom kode_rekening, berdasarkan id_layanan & pemesanan tersebut dapat digunakan untuk diambil total melalui tabel  pemesanan_layanan sehingga total pendapatan diambil dari tabel  pemesanan_layanan berdasarkan tanggal bayar yang ada di tabel "pembayaran".

relasi antara tabel pembayaran dengan pemesanan terdapat pada tabel "pemesanan_pembayaran"


5. Pengeluaran
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/b44bb5bf-ff3d-415c-ae24-4240565451d1)

Untuk mendapatkan nilai pengeluaran maka perlu diambil dari beberapa tabel "transaksi" untuk mendapatkan total nominal 
tentu berdasrkan tabel ini gunakan kode rekening untuk mendapatkan jenis transaksinya melalui tabel "**kode_rek3**" gunakan tabel ini untuk mendapatkan total pengeluaran untuk 1 jenis pengeluaran berdasarkan kode rekening yang berada di bawah sub rekening "**kode_rek3**" . 

lalu untuk judul besarnya diambil berdarkan "**kode_rek2**" 

contoh seperti berikut ini : 
<img width="604" alt="1" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/c3cdfbc0-c009-4ce0-bffd-8bebb092ef12">

**Comment by pandigresik** [comment]
> untuk pendapatan dapat diambil berdasarkan tabel "pemesanan" dengan "status_pembayaran = 1 " sehingga tidak perlu menentukan berapa yang dibayar berdasarkan pembayaran termin namun jika dalam pemesanan status_pembayaran = 1 maka semua pemesanan pada tabel "pemesanan_layanan" telah dibayar lunas.

misalkan ada case membayar dengan bertahap, pemesanan dengan jumlah 2 juta pada tanggal 30 juni dimana dilakukan pembayaran sebesar 750 ribu pada tgl 30 juni dan 1,25 juta pada tgl 1 juli jam 21:00 . Apakah semuanya akan masuk pada laporan bulan juli karena lunas pada juli ? 

Jika mengacu pada keterangan 

> maka tinggal menyusun tampilan laporan berdasarkan kode rekening, pertama lihat kode rekening yang dikaitkan berdasrkan tabel layanan pada kolom " kode_rekening" namun tabel tersebut disusun berdaskan tabel kode_rek1 kategori pengeluaran lalu looping sampai dengan kode_rek4 maka kode_rek4 yang dapat dikaitkan pada tabel layanan di kolom kode_rekening, berdasarkan id_layanan & pemesanan tersebut dapat digunakan untuk diambil total melalui tabel pemesanan_layanan sehingga total pendapatan diambil dari tabel pemesanan_layanan berdasarkan tanggal bayar yang ada di tabel "pembayaran".

Maka ketika kita buka laporan tgl 1 juli jam 09:00 maka 750 ribu belum dimasukkan sebagai pendapatan dikarenakan status pembayaran belum lunas, namun ketika kita buka lagi laporan pada 1 juli jam 22:00 maka ada pendapatan sebesar 750 ribu di bulan juni. Sehingga terjadi perbedaan pendapatan untuk laporan bulanan ketika dibuka pada tgl 1 juli pagi dengan 1 juli malam hari diatas jam 21:00

**Comment by pandigresik** [comment]
> ![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/a9b059b7-4073-4fd7-83a5-46bb3de05892)

berdasarkan keterangan diatas, maka kolom ketiga diambil dari rek_3 namun setelah kami cek untuk mug, pdh dan  kaos tidak ada di rek_3 justru berada di rek_4. Apakah memang kode rekeningnya belum lengkap ?

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/b73eb7d3-9042-4ead-b755-890561b3c8e4)

**Comment by pandigresik** [comment]
Contoh lain pada format laporan contoh ada klasifikasi bunga bank
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/9bb3c362-242e-46d9-9419-b2eab29da018)
Karena berada pada kolom 2, seharusnya ambil dari rek_2 namun kami cek tidak ada bunga bank pada rek_3 justru bunga bank ditemukan pada rek_4

tidak ada bunga bank pada rek_3 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/85f9614f-37b9-44d4-9055-50407d9d07b3)
bunga bank ditemukan pada rek_4
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/70e190d8-f6be-4491-933e-72592bfdf06d)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/616
