### ISSUE TITLE
Buat core sistem dengan laravel untuk pemngembangan master laravel bagi layanan baru

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#441]
Issue ini digunakan untuk membuat core awal standart yang digunakan pada framework laravel. 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/f4549e19-0113-4b15-844c-5d01bfc1e52f)

[Layanan Admin.zip](https://github.com/OpenSID/wiki-layanan-opendesa/files/13592853/Layanan.Admin.zip)

berikut terlampir file asset tampilan admin LTE dan susunan menu yang digunakan. 

Batasan pengerjaan issue sebagai berikut : 

1. Buat tujuan ke 1 branch dengan nama layanan-laravel
2. Lalu pasang standar framework laravel beserta paket - paket yang digunakan 
3. lalu pasang asset admin LTE sesuai tampilan yang diatas agar untuk seterusnya tinggal menyusun menu & tampilan setiap modul.

**Comment by agungsugiarto** [comment]
Mas @vickyrolanda bisa di test di branch

https://github.com/OpenSID/Layanan_OpenDESA/tree/layanan-laravel
