### ISSUE TITLE
Tambah informasi di Laporan > Laporan Premium

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#442]
Tambah informasi seperti terlihat di gambar di bawah.

1. Tambah baris di atas yg menampilkan total pelanggan Premium yg aktif 
2. Pada jumlah pelanggan per kabupaten, tambahkan info jumlah tersebut merupakan berapa persen dari total pelanggan Premium, di dalam kurung, dibulatkan ke dua desimal
3. Bisa sortir setiap kolom
4. Pada info Bulan Ini dan Bulan Lalu, pecah masing2 menjadi tiga bagian:

    1.  Jumlah pelanggan baru
    2. Jumlah perpanjangan layanan yg sudah ada
    5. Jumlah pelanggan yg habis masa langganan dan tidak memperpanjang

<img width="1395" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/f34cdbbb-3924-40d1-a597-48b74e3aab2c">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/593
