### ISSUE TITLE
Jumlah dan rincian tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#45]
[laporan-pemesanan-layanan-2022-01-01 - 2022-01-31 (1).xlsx](https://github.com/OpenSID/wiki-layanan-opendesa/files/7855097/laporan-pemesanan-layanan-2022-01-01.-.2022-01-31.1.xlsx)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/Layanan_OpenDESA/pull/35
