### ISSUE TITLE
Fitur hapus Dasbor SiapPakai

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#452]
- [x] tambahkan model TemaDasborSiapPakai
- [x] Tambahkan validasi pengecekan pemesanan yang akan dihapus
- [x] Buat fungsi hapus data dasbor siappakai
- [x] buat fungsi hapus data tema siappakai yang berkaitan dengan dasbor siappakai
- [x] Kirim data API ke SiapPakai

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/356
