### ISSUE TITLE
Kesulitan Mengetahui Informasi Jenis Layanan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#48]
Saat ini pada menu Laporan Layanan hanya tercantum jumlah pemesanan.
Jika memungkinkan dapat diberi akses link khusus untuk melihat tabel daftar desa sesuai jumlah pemesanan dan sesuai jenis layanan tersebut.

**Comment by FirlianiF** [comment]
Issue ini sudah dikerjakan, saat ini sudah tersedia tombol pada jumlah pemesanan beserta link  yang akan masuk ke halaman detailnya
