### ISSUE TITLE
Total desa di halaman Laporan Premium salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#483]
<img width="1395" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/0775383a-26c7-47de-b438-b9cff08a5290">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/378
