### ISSUE TITLE
Bug pencarian pada layanan ( konversi laravel )

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#484]
Terjadi error ketika melakukan pencarian pada datatable

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/2f039421-c331-432b-ac92-2079cbeb7852)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/443
