### ISSUE TITLE
Gabung Kontak dengan Nomor Hp yangSama 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#49]
Saat ini masih bisa tambah kontak dengan nama dan nomor hp yg sama pula.

Sebaiknya jadi 1 agar tidak ada duplikasi kontak yg sama, tentu akan menyulitkan jika suatu saat ada fitur rekap berdasarkan kontak.

**Comment by FirlianiF** [comment]
Tambah validasi nomor hp 08 dan +62 (seragamkan), tidak boleh ada spasi, validasi minimal nomor hp.

**Comment by devrakapriyo** [comment]
https://github.com/OpenSID/Layanan_OpenDESA/pull/184
