### ISSUE TITLE
Belum tersedia Laporan Perbandingan Bulan Lalu dan Bulan ini di Tanggal yang Sama

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#50]
Diperlukan sebagai bahan evaluasi.

**Comment by vickyrolanda** [comment]
Diperlukan Laporan perbandingan bulan lalu dan bulan ini , untuk fitur ini tambahkan 1 menu baru di menu laporan dengan nama  "Laporan Perpandingan"  , Laporan ini mengambil data 1 bulan ke belakang / 1 tahun kebelakang dengan tambahan filter hanya untuk range bulan & tahun  (tidak untuk range hari). 

jika Pilih bulan Mei 2024 maka perpandingannya H-1 (yaitu Bulan yang dipilih  - 1 bulan kebelakang ) 
jika dipilih Tahun 2024 maka perpandingannya H-1(Yaiut Tahun yand dipilih - 1 tahun kebelakang)

Bentuk laporannya seperti berikut ini  : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/568451ca-04ba-4b0c-94a6-3261eb19a2ce)

untuk fitur tambahan : 

- [ ] Filter Bulan & tahun 
- [ ] Fitur Export Excel

**Comment by apidong** [comment]
menurut saya lebih bagus kalau dibuat menggunakan  2 datetimerange picker. sehingga bisa memfilter range tanggal yang lebih luas.
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/67b8193c-6d77-4714-932a-f586a503dd09)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/567
