### ISSUE TITLE
Pemesanan Layanan Berupa Modul

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#506]
- [ ] Perlu disediakan pilihan jenis layanan yang berupa modul.
Contoh :
<img width="450" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/57283157/7a530217-ae76-4603-88e7-a61e02afe2de">

- [ ] Daftar jenis layanan yang berupa modul diambil dari modul beserta harganya yang bisa diubah.

- [ ] Tambahkan kategori berupa modul

**Comment by agungsugiarto** [comment]
mas @vickyrolanda issue ini statusnya dari awal cek issue, mohon dilengkapi sebelum di assign

**Comment by vickyrolanda** [comment]
issue ini perlu ada perubahan pada penambahan jenis layanan yang di kaitkan dengan modul yang tersedia pada layanan,
terdapat 2 bagian pada ketersediaan modul ini bukan hanya modul namun juga perlu diterapkan untuk tema. 

Yang perlu di kerjakan adalah : 

- [ ] Tambahkan 2 input radio pilihannya ( Modul & Tema)
- [ ] Jika pilihan modul maka harus memilih modul yang mana (bisa memilih  lebih dari 1 modul)
- [ ] Jika pilih Tema maka perlu memilih tema yang mana (bisa memilih lebih dari 1 tema)

Sehingga ada jenis layanan yang terkait ke modul & tema

**Comment by pandigresik** [comment]
> issue ini perlu ada perubahan pada penambahan jenis layanan yang di kaitkan dengan modul yang tersedia pada layanan, terdapat 2 bagian pada ketersediaan modul ini bukan hanya modul namun juga perlu diterapkan untuk tema.
> 
> Yang perlu di kerjakan adalah :
> 
> * [ ]  Tambahkan 2 input radio pilihannya ( Modul & Tema)
> * [ ]  Jika pilihan modul maka harus memilih modul yang mana (bisa memilih  lebih dari 1 modul)
> * [ ]  Jika pilih Tema maka perlu memilih tema yang mana (bisa memilih lebih dari 1 tema)
> 
> Sehingga ada jenis layanan yang terkait ke modul & tema

Penambahan ini ketika buat pemesanan atau entri jenis layanan baru ?
Sebagai informasi saat ini pada tabel pemesanan_layanan yang disimpan adalah layanan_id dan itu dibaca dibanyak tempat juga

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/565
