### ISSUE TITLE
Tampilkan jumlah desa di laporan kabupaten (pengguna premium)

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#51]
![image](https://user-images.githubusercontent.com/249563/150451262-71e47caf-fc7e-4f9c-ada4-4fab8af3ab34.png)

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, @agungsugiarto untuk Laporan kabupaten (pengguna premium) jumlah desa akan selalu sama dengan jumlah premium. Apakah mau dibedakan yakni : 
1. Jumlah desa (semua layanan)
2. Jumlah premium (hanya layanan premium)

atau 
1. Jumlah desa (hanya layanan premium)
2. Jumlah premium (hanya layanan premium yg masih aktif)

![layanan](https://user-images.githubusercontent.com/57283157/155269254-21796b0a-41a4-428e-b7f2-7bd04394f0e8.png)

**Comment by eddieridwan** [comment]
@andifahruddinakas jumlah desa yg diperlukan adalah jumlah desa di kabupaten ybs, di mana info tsb dapat diambil dari TrackSID. Sebagai contoh jumlah desa di Kab Batu Baru adalah 141 dan Kab Lampung Tengah 301. Tujuannya untuk melihat berapa desa lagi dari masing2 kabupaten yg berpotensi juga mengambil langganan premium.

Mohon sekalian ganti judul laporan menjadi Laporan Pelanggan Per Kabupaten
