### ISSUE TITLE
Tampilan informasi PPH pada hasil cetak dan preview faktur layanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#516]
Setelah menambah fungsi PPH pada layanan maka setiap faktur perlu ditambahkan informasi pajak. 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/b8976b23-3692-454c-9259-7bdb1a6f5794)

Sesuaikan seperti berikut ini : 

- [ ] Sesuaikan hasil cetak faktur
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/a53f4751-52d0-4a92-8553-457909a7664a)
- [ ] Sesuaikan di form pemesanan
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/026da4f2-e38b-4337-ae7b-e55788910c5f)

- Cek juga pada API Faktur http://127.0.0.1:8000/api/v1/pelanggan/pemesanan/faktur?invoice=INV/20240217/Dco3wfvc 
-  Cek juga pada API deskripsi faktur http://127.0.0.1:8000/api/v1/pelanggan/pemesanan/deskripsi-faktur?invoice=INV/20240217/Dco3wfvc
- api juga perlu disesuaikan

**Comment by agungsugiarto** [comment]
mas @vickyrolanda perlu informasi lebih spesifik, bagaimana perhitungan pph.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/448
