### ISSUE TITLE
Laporan Layanan tampilkan yg aktif saja

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#53]
Saat ini Laporan Layanan menampilkan jumlah semua layanan meskipun sudah tidak aktif.

![image](https://user-images.githubusercontent.com/249563/151694991-ac9adf25-6cc5-455e-9b0b-5f74b08160c5.png)

**Comment by apidong** [comment]
siap

**Comment by apidong** [comment]
@eddieridwan apakah hanya yang dilingkari saja yang di filter status aktif. yang tidak dilingkari statusnya dihiraukan?

**Comment by eddieridwan** [comment]
@apidong ada layanan yg tidak berbatas waktu, seperti tema pro dan anjungan. Layanan seperti itu dianggap selalu aktif. Jadi pastikan filter aktif yg diterapkan tidak mempengaruhi layanan seperti itu, yg selalu tampil.
