### ISSUE TITLE
Peyesuaian pemasangan modul opensid di siappakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#536]
Issue ini menyesuaiakan issue yang ada di SiapPakai yaitu https://github.com/OpenSID/wiki-saas/issues/358

pada saat `select` berdasarkan `status_langganan` pada table `pelanggan` yang aktif (1), sedangkan yang ada di data adalah status_pelanggan bermacam seperti pada gambar berikut:

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/cdc6d6e5-fde5-4533-ae8f-964987a142b5)

sehingga agar dapat menampilkan modul di siappkai `select` berdasarkan `status_langgan` yang bukan 2 dan 3.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/446
