### ISSUE TITLE
Sesuaikan data pada pemesanan bulan ini

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#548]
Cek daftar data pada pemesanan bulanini karena saat ini data yang tampil ada yang muncul pemesanan 2 bulan lalu yang perlu di cek dan diperbaiki adalah : 

- [x] Pemesanan yang diperpanjang akan tampil pada pemesanan bulan ini
- [x] Pastikan data yang tampil hanya pemesanan yang terjadi di bulan ini, pemesanan bulan lalu tidakperlu ditampilkan berdasarkan tanggal nota

**Comment by FirlianiF** [comment]
mas @vickyrolanda mohon dilengkapi issue nya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/452
