### ISSUE TITLE
Perbaikan pada layanan laravel

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#549]
ketika dilakukan pemeriksaan pada beta.opendesa.id maka muncul seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/aae771cf-54af-4f52-8a9c-6cc552d0863d)

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/61280c83-02a0-4965-a711-13b350d7638a)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/451
