### ISSUE TITLE
Bug : Edit Pemesanan jenis layanan tidak tampil

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-layanan-opendesa#557]
jika pemesanan belum lunas, pilihan jenis layanan tidak tampil dan tidak bisa diubah
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/e33d11d5-7e70-47c5-b51a-f9cb39cb6a90)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/460
