### ISSUE TITLE
Penyesuaian data pelanggan tidak bisa di hapus & di edit jika sudah memiliki layanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#590]
Untuk menyempurnakan tugas dari menu pelanggan kita perlu menyesuaikan beberapa hal : 

- [x] Periksa jika pelanggan memiliki layanan maka tidak dapat di hapus
- [x] Periksa jika pelanggan memiliki layanan maka untuk wilayah terdisable tidak bisa diubah kecuali pilihan desa
- [x] Tambahkan fungsi aktif & non aktif untuk pelanggan 
- [x] Tambahkan Filter aktif & non-aktif pada datatable pelanggan
- [ ] Tambahkan fungsi pemeriksaan jika pelanggan di non-aktifkan maka untuk desa tersebut dapat ditambah pelangan baru
- [ ] Tambahkan fungsi periksa jika terdapat 2 pelanggan dengan desa yang sama maka salah 1nya tidak dapat diaktifkan artinya yang dapat aktif hanya 1 pelanggan saja.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda , Poin ini sangat riskan karena diawal sudah didesain (database field `desa_id`) agar pelanggan tidak duplikat, karena pertimbangan apa pelanggan harus duplikat?

- [ ] Tambahkan fungsi pemeriksaan jika pelanggan di non-aktifkan maka untuk desa tersebut dapat ditambah pelangan baru
- [ ]  Tambahkan fungsi periksa jika terdapat 2 pelanggan dengan desa yang sama maka salah 1nya tidak dapat diaktifkan artinya yang dapat aktif hanya 1 pelanggan saja.

**Comment by vickyrolanda** [comment]
itu hasil diskusi dengan pelaksana, misalkan begini 1 desa sebelumnya berlanggnan dengan mitra A, namun sudah lama tidak diperpanjang dengan alasan tertentu maka desa tersebut memutuskan untuk menghubungi OpenDesa langsung. 

maka ketika ingin ditambahkan ternyata desa tersebut sudah terdaftar namun kontak langgannya berbeda jika diupdate maka kita akan kehilangan data pelanggan yang lama serta kita tidak ingin mengikuti layanan yang lama ke desa yang baru mau bergabung lagi dengan data pelanggan yang sama , kita mau pelanggannya baru sehingga riwayat pemesanannya juga akan mulai dari yang baru.

maka itu ada status aktif & non-aktif agar dapat membedakan pelanggan yang aktif & tidak, kalo di suspend itu masih ada kemungkin bisa kembali namun kalo sudah non-aktif artinya tidak ada kabar apapun dari pelanggan untuk memperpanjang layanannya.

pertimbangan diatas mas @agungsugiarto  yang menjadi salah satu alasan knpa pelanggan itu memang hanya boleh 1 yang aktif namun tidak menutup kemungkinan 1 desa punya riwayat didaftarkan oleh siapapun dan kita perlu bedakan dan simpan riwayat itu hanya untuk pelanggan itu saja tidak campur.

**Comment by eddieridwan** [comment]
@vickyrolanda @agungsugiarto perhatikan bahwa solusi jangka panjangnya adalah **mengharuskan adanya kontak pemdes** (selain kontak pegiat) direkam di aplikasi Layanan untuk SETIAP pelanggan. Seharusnya sudah ada issue untuk menerapkan keharusan itu. 

Di mana ada sengketa antara desa dan pegiat, maka yg dianggap sah adalah kontak pemdes. Dan setiap saat pemdes dapat melakukan transaksi langganannya, asal menggunakan kontak yg tercatat di Layanan.

Harap solusi sementara apapun yg diterapkan dirancang supaya konsisten dengan solusi jangka panjang tersebut.

**Comment by agungsugiarto** [comment]
@vickyrolanda @eddieridwan menurut saya data pelanggan seharusnya tidak duplikat, solusi untuk melihat history detail pelanggan sebelum dirubah seharusnya cukup ditambahkan di history pemesanan yg sekarang sudah ada. Contoh: data layanan walaupun harga dirubah tapi tetap ada history di detail pemesanan.

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/10989147/1fda6245-0569-4b8a-8bd7-7ac529dfcf95)

**Comment by agungsugiarto** [comment]
issue terpisah dibahas dengan pelaksana

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/523
