### ISSUE TITLE
Perpanjangan premium massal yang berbasis PKS

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#592]
Untuk issue ini terjadi pada saat Kota BIMA yang terdiri dari 41 kelurahan yang akan melakukan perpanjangan premium, jika dilakukan satu per satu maka akan cukup membutuhkan waktu, sehingga kurang efektif apalagi jika desa pada suatu kabupaten terdapat 200 desa atau lebih. Sehingga perlu dilakukan perpanjangan premium secara masal dengan berbasis PKS, contoh Kota Bima, Kabupaten Bima, Kabupaten Tabanan.

-----------------------
fungsi perpanjang premium massal dapat dilakukan beberapa tahap : 

- [ ] Tambahkan tombol baru "Perpanjang Masal"  & Input checkbox 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/ef580261-44fc-4594-85d3-01293ba38202)

- [ ] Ketika klik tombol perpanjangan massal maka pergi ke halaman tersendiri : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/41fa1b05-e867-4eba-b096-429d4d0e8f6c)
- di halaman ini desa tetap bisa ditambah dan bisa di hapus
- selebihnya sama seperti perpanjangan seperti biasa

**Comment by vickyrolanda** [comment]
Masih Perlu disesuaikan.
- Bentuk invoicenya seperti apa ? 
- Mekanisme perlu diperjelas sebelum di kerjakan.

**Comment by vickyrolanda** [comment]
mas @agungsugiarto sudah sy lengkapi issue ini bisa mengikuti intruksi yang ada di deskripsi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/538
