### ISSUE TITLE
Otomatis https://

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#6]
Sekarang jika kita entry pelanggan, maka diminta menulis alamat domain lengkap dengan protocol, contoh : https://bajang.opendesa.id

Yang diharapkan :
domain ditulis tanpa prefix protocol nya. jadi cukup Full Domain Name saja (contoh : bajang.opendesa.id) jadi ditulis tanpa https://

**Comment by agungsugiarto** [comment]
Terimakasih pak @roaddee,

Issue ini saya tutup karena sudah saya perbaiki.
