### ISSUE TITLE
Jumlah Desa salah di Laporan Kabupaten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#60]

**Comment by eddieridwan** [comment]
Saat ini sepertinya kolom Jumlah Desa menunjukkan jumlah desa pelanggan di suatu kabupaten. Padahal yg diperlukan adalah total keseluruhan desa yang ada di kabupaten tersebut.

![image](https://user-images.githubusercontent.com/249563/158003160-4ac21dc2-f036-4c4b-a194-4dbb1e2e89f8.png)

**Comment by FirlianiF** [comment]
Pengerjaan ditunda, menunggu disediakannya API terkait di tracksid https://github.com/OpenSID/tracksid/issues/130.

**Comment by eddieridwan** [comment]
@FirlianiF , karena bung @scqolbu24 perlu fokus pada OpenSID SiapPakai dan konversi PBB, silakan Firli saja yg mengerjakan tugas https://github.com/OpenSID/tracksid/issues/130

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/159
