### ISSUE TITLE
Perjelas Aturan Masa Berlaku Premium

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#61]
Ambil contoh mudah dalam 1 tahun,
Desa mulai berlangganan 1 Januari 2021, maka akhir langganan tanggal 31 Desember 2021.

Tanggal berakhir bukan berarti adalah Hari dimana Desa tersebut sudah putus hubungan, tetapi Tanggal Akhir berlangganan.
(Tanggal akhir tersebut masih berstatus pelanggan).

Contoh lain, mulai berlanganan 5 Mei 2022, maka akhir langganan tanggal 4 Mei 2022.
Menandakan bahwa, desa tersebut masa berlangganan masih aktif di tanggal 4 mei 2022.
(bukan sudah dianggap berakhir).

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/48
