### ISSUE TITLE
Import pelanggan perkabupaten beserta pesanan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#614]
Proses Import pelanggan dan pemesanan dapat dilakukan beberapa langkah : 

1. Download Template 
2. Pilih Template yang sudah disesuaikan datanya 
3. Import file ( proses ini lakukan untuk menyimpan data pelanggan dan alihkan ke halaman tersendiri untuk memilih layanan ) 
4. Proses pilih layanan dan untuk daftar pelanggan sudah ter list pada halaman ini 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/0131c565-a41f-49ce-8a34-ed65a70f4341)
   - Di halaman ini pelanggan bisa ditambah atau di kurangi 
5. Setelah itu simpan maka proses import dan tambah pesanan untuk sekaligus data sudah berhasil dilakukan

**Comment by apidong** [comment]
@scqolbu24 apakah ada format baku file yang akan di import?

**Comment by scqolbu24** [comment]
saat ini belum ada mas @apidong, bisa diambil dari tabel pelanggan mas

**Comment by apidong** [comment]
ini bisa dikerjakan jika https://github.com/OpenSID/Layanan_OpenDESA/pull/538 sudah di merge

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/629
