### ISSUE TITLE
Sesuaikan pilihan pelanggan berdasarkan status yang aktif saja

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#615]
saat fungsi dari issue ini https://github.com/OpenSID/wiki-layanan-opendesa/issues/590 di terapkan maka perlu disesuaikan berikut beberapa yang perlu di sesuaikan :  Tampilkan data desa yang aktif saja

- [ ] Halaman tambah pemesanan
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/8af96d0d-dc5a-42cd-993d-dac208c7abf1)

- [ ] Halaman tambah  pemesanan siappakai 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/b940cf68-15bb-4f40-8c2d-f22b61833536)

**Comment by agungsugiarto** [comment]
Catatan: 
Poin 2 otomatis tidak tampil karena sudah tidak bisa menambahkan dari poin 1
Halaman tambah pemesanan siappakai

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/524
