### ISSUE TITLE
Bedakan pelanggan Paket SiapPakai dengan pengguna Dasbor SiapPakai Diskominfo

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#618]
Saat ini Layanan tidak membedakan antara pelanggan Paket SiapPakai dengan pengguna Dasbor SiapPakai Diskominfo.

<img width="1384" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/249563/18f4c145-92ef-460a-ba3a-2c80bd89b448">

Padahal ketentuan dan penanganan kedua kelompok ini berbeda. 

Perbaiki supaya aplikasi Layanan membedakan antara kedua kelompok tersebut. Misalnya:

1. Pelanggan Layanan Paket SiapPakai diberi judul Jenis Layanan `Paket SiapPakai`; dan
2. Pengguna Dasbor SiapPakai Diskominfo diberi judul jenis Layanan `SiapPakai Diskominfo`.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/536
