### ISSUE TITLE
Masa Berakhir Langganan Masih Rancu

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#62]
Desa yang berakhir misal tanggal 12 Mei 2022, tentu sudah lakukan update versi 22.05 karena masih berhak dapat update bulan tersebut.

Namun ternyata desa yang akhir masa langganan di tanggal 12 Mei 2022, opensid versi 22.05 akan terkunci.

Seharusnya masih tetap dapat menggunakan versi 22.05 yang sudah berhasil dan jalankan versi tersebut di bulan berjalan.

Begitupula jika ada bug sehingga rilis versi rev01 sampai rev04 sekalipun, desa masih berhak pakai versi 22.05

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/48

**Comment by andifahruddinakas** [comment]
Untuk pelanggan akhir masa langganan misalnya tanggal 12 Mei 2022, masih berhak menerima update versi v22.05-premium maupun versi rev nya. Yang dibatasi hanya update versi di atasnya, misal v22.06-premium atau versi rev nya. Jika terlanjur di update, script tidak akan berjalan sebagai mana mestinya (harus di downgrade ke versi terakhir masa aktif)
