### ISSUE TITLE
Ubah cetak faktur ke dalam bentuk pdf

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#620]
Saat ini faktur dibuat pda halaman cetak yang masih dapat di ubah menggunakan inspect , maka perlu diubah ke dalam bentuk PDF karna ini juga berfungsi untuk menjadi file yang dapat di kirim melalui WA atau Email.

saat ini seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/0eec01fa-5097-4bf6-88ff-353eb7603c47)
[Layanan OpenDesa - Faktur INV_20240506_ahxCBuc6.pdf](https://github.com/OpenSID/wiki-layanan-opendesa/files/15217254/Layanan.OpenDesa.-.Faktur.INV_20240506_ahxCBuc6.pdf)

**Comment by apidong** [comment]
> Saat ini faktur dibuat pda halaman cetak yang masih dapat di ubah menggunakan inspect , maka perlu diubah ke dalam bentuk PDF karna ini juga berfungsi untuk menjadi file yang dapat di kirim melalui WA atau Email.
> 
> saat ini seperti berikut ini : ![image](https://private-user-images.githubusercontent.com/59082428/328090341-0eec01fa-5097-4bf6-88ff-353eb7603c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTAzNTEsIm5iZiI6MTcxNTE5MDA1MSwicGF0aCI6Ii81OTA4MjQyOC8zMjgwOTAzNDEtMGVlYzAxZmEtNTA5Ny00YmY2LTg4ZmYtMzUzZWI3NjAzYzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE3NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZTI5YzBmYTZhMjEwMTdiMDRjMzliYzcwNWRlYTBiZWE1ODMzOTEwM2QwYTA2ZjFmMWUwNWNhMjZkYTI0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yHOOtTlzXgBhanu1EGWMrxisK0lrFyvJmWb51wAbjU) [Layanan OpenDesa - Faktur INV_20240506_ahxCBuc6.pdf](https://github.com/OpenSID/wiki-layanan-opendesa/files/15217254/Layanan.OpenDesa.-.Faktur.INV_20240506_ahxCBuc6.pdf)

mungkin perlu di cek juga apakah akan berefek dengan invoice yang ada di opensid.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/532
