### ISSUE TITLE
Nama Desa tidak mengikuti ubahan terbaru

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-layanan-opendesa#623]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/6c5add18-c835-4fa8-9809-d5a68b9afebc)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/531
