### ISSUE TITLE
Ketika Pelanggan Paket SiapPakai dan SiapPakai Diskominfo melakukan perpanjangan, maka otomatis update token dan berakhir langganan di data pelanggan pada Dasbor SiapPakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#625]
Data Pelanggan di Dasbor SiapPakai

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/95d4c4a0-7363-4d6e-90d9-05024a636951)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/539
