### ISSUE TITLE
Automasi backup pada panduan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#628]

**Comment by apidong** [comment]
[backup_wikijs.txt](https://github.com/user-attachments/files/16087990/backup_wikijs.txt)
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/9f8f87b2-6a19-4275-8e74-88b00d047835)
rename extension menjadi .sh dan isi varible2 konfigurasinya

jalankan perintah 
`chmod +x backup_wikijs.sh`

tambahkan ke cronjob dengan cara
`crontab -e`

tambahkan baris 
`0 16 * * * /path/to/backup_wikijs.sh >> /path/to/log/backup_cron.log 2>&1`

atau ganti jamnya sesuai jadwalnya 
bisa generate melalui https://crontab.guru/

**Comment by scqolbu24** [comment]
hasil backup database panduan secara otomatis ke google drive 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/6c8226e0-dd3d-4fad-8a9f-744a7385de1e)
