### ISSUE TITLE
Paksa Stop Migrasi DB

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#63]
Jika desa berakhir masa langganan di bulan Mei 2022, dan ketika desa tersebut memaksa untuk update ke 22.06,
maka semua menu akan terkunci kembali.

Paksa untuk tidak lakukan migrasi DB yang diterapkan di 22.06 (jika ada), agar desa tersebut dengan mudah kembali ke 22.05 karena struktur tabel masih belum terpengaruh ketika mencoba update ke 22.06

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1060
