### ISSUE TITLE
Sesuaikan sumber data pengeluaran pada kode rekening yang tersedia

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#630]
saat ini untuk pendapatan sudah dapat ditentukan sumber datanya seperti berikut ini : 
<img width="722" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/d23ab76b-2873-42dd-a243-035701c7634e">

namun untuk pengeluaran belum dapat di ambil sumber datanya , karena sudah ada menu pengeluaran maka perlu ditambahkan sumber data kode rekening pengeluaran.

<img width="740" alt="image" src="https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/36215d33-c90c-447f-a521-cd1a06bc4b6f">

**Comment by apidong** [comment]
> saat ini untuk pendapatan sudah dapat ditentukan sumber datanya seperti berikut ini : <img alt="image" width="722" src="https://private-user-images.githubusercontent.com/59082428/332206483-d23ab76b-2873-42dd-a243-035701c7634e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjMxMzIsIm5iZiI6MTcxNzkyMjgzMiwicGF0aCI6Ii81OTA4MjQyOC8zMzIyMDY0ODMtZDIzYWI3NmItMjg3My00MmRkLWEyNDMtMDM1NzAxYzc2MzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA4NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNGRmMDM4MzY3YWU1ZmYxN2QzNzUwMDFhYmJjZmEzZTNiZjI1MGMxMTIwNmNiMTg5MTdmNjJmOGEwYmE0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPur0eRmckNVOR-gR6LtNPTec2nheP6q5yjvtZEFhe0">
> 
> namun untuk pengeluaran belum dapat di ambil sumber datanya , karena sudah ada menu pengeluaran maka perlu ditambahkan sumber data kode rekening pengeluaran.
> 
> <img alt="image" width="740" src="https://private-user-images.githubusercontent.com/59082428/332206705-36215d33-c90c-447f-a521-cd1a06bc4b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjMxMzIsIm5iZiI6MTcxNzkyMjgzMiwicGF0aCI6Ii81OTA4MjQyOC8zMzIyMDY3MDUtMzYyMTVkMzMtYzkwYy00NDdmLWE1MjEtY2QxYTA2YmM0YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA4NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Nzg2MTEyMWQyMTI4MzU3ZTJkZmY0MjI3NmE5MTM3YTk3NDY1YTFjNTI4NzRlZTI4ZDEzNGU2NWNlMDM2OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XUKyj8m4UnB5-cElHYY_9w4LUIzS4aOdwZZR15jdzeI">

ini saya ubah langsung di form pengeluaran
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/ed0fd063-fe21-4279-8d78-3422c37ac678)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/570
