### ISSUE TITLE
Data pemesanan bulan ini tidak sesuai jumlah di samping menu dengan data yang ditampilkan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#631]
![Screenshot 2024-05-21 110400](https://github.com/OpenSID/wiki-layanan-opendesa/assets/30171560/4afdac40-923d-4eef-89ae-243702c6b80d)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/542
