### ISSUE TITLE
BUG: field is_delete di table layanan

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/wiki-layanan-opendesa#638]
Bug ini berkaitan dengan pr https://github.com/OpenSID/Layanan_OpenDESA/pull/483 field is `is_delete` di table `layanan` sudah dihabus berganti dengan softdelete laravel.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/552
