### ISSUE TITLE
Buat Baris warna Berbeda pada Layanan yang berstatus Belum Lunas

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#64]
Ketika masuk menu Layanan Pelanggan, seluruh desa status aktif, namun belum ada penjelasan jika desa tersebut ada yang bersatus belum Lunas.

Sebaiknya diberi tanda khusus pada baris desa yang berstatus belum lunas, misal beri baris warna merah, atau kuning, atau lainnya.

Agar dapat segera ditindaklanjuti ketika sudah dinyatakan lunas. (menghindari pelaksana lupa mengganti status).

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/59
