### ISSUE TITLE
Perlu dibuat halaman khusus untuk permintaan kerjasama

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#647]
Halaman kerja sama khusus untuk melihat desa / pelanggan mana saja yang telah meminta kerja sama & yang belum meminta kerja sama, juga perlu dibuatkan semacam halaman khusus yang membedakan antara pengguna yang telah kerja sama & yang belum kerja sama. 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/4160f567-f0d5-4516-a495-46178684a5e4)

Tambahkan Menu Kerja Sama  dan buat halaman tersendiri untuk masing-masing berikut ini: 

- [ ] Permintaan Kerja Sama
- [ ] Daftar Kerja sama
- [ ] Daftar Yang belum kerja sama
- [ ] Daftar yang di tolak

issue ini dikerjain khusus daftar permintaan kerja sama dan di issue yang berbeda bisa kerjakan untuk : 

- [x] #654
- [x] #655
- [x] #656

**Comment by pandigresik** [comment]
Kriterianya apa untuk daftar pelanggan dengan status :

1. Permintaan Kerja Sama
2. Daftar Kerja sama
3. Daftar Yang belum kerja sama
4. Daftar yang di tolak

Saat ini pada tabel pelanggan ada kolom permohonan dan status_langganan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/564
