### ISSUE TITLE
Permudah Verifikasi Pendaftaran Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#65]
Saat ini untuk lakukan cek dokumen permohonan kerjasama tidak dapat diakses melalui Mobile, sehingga dapat menunda proses aktivasi yang seharusnya dapat dilakukan secara realtime sesuai notifikasi yang diterima di telegram saat ada permohonan baru.

Yang berlaku saat ini hanya bisa dilihat melalui lapotp/pc, dan itupun lebar layar PDF kecil sekali, berdampak pada terlalu banyak scroll untuk membaca dokumen.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR #56 perbaiki lihat dokumen https://github.com/OpenSID/Layanan_OpenDESA/pull/56
