### ISSUE TITLE
Perjelas Status Permohonan Kerjasama

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#66]
Ketika desa ajukan permohonan kerjasama dan dinyatakan belum valid, maka pelaksana melakukan klik "Batalkan Pendaftaran" pada Layanan OpenDesa.

Saat ini tidak ada tanda bahwa desa tersebut sudah pernah ditolak sebelumnya atau belum, sehingga bisa 2 atau 3 kali atau bahkan lebih pelaksana A, B, C dapat melakukan hal yang sama, (mubazir).

Sebaiknya ada tanda khusus (warna baris berbeda) dan nonaktifkan tombol Batalkan Pendaftaran ketika sudah dilakukan pembatalan oleh salah satu pelaksana.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/60
