### ISSUE TITLE
Sesuaikan query data & jumlah data layanan di laporan layanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#669]
Saat ini jumlah laporan pada layanan masih berbeda dengan jumlah yang terekap manual karena pada laporan layanan masih mengikuti data pesanan yang batal, contoh lihat total pesanan premium bulan lalu : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/bc539992-23db-4898-92d0-5a223d51f642)

Lalu cek pesanan pada menu pemesanan seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/faa65d86-5f8b-43a2-af34-32b1dd30df0f)

jika di lihat ada selisi pada laporannya, sehingga yang perlu masuk pada laporan layanan adalah pesanan yang lunas saja, jika ada pesanan yang dibatalkan maka tidak masuk pada rekapannya.

**Comment by apidong** [comment]
bukannya sama denga ini https://github.com/OpenSID/wiki-layanan-opendesa/issues/659

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/580
