### ISSUE TITLE
Proses Perpanjangan Layanan Terkunci

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#67]
Ketika ada desa yang berlangganan misal layanan Premium tanggal 22 Oktober 2020 dan akhir langganan 21 Oktober 2021, lalu lupa untuk perpanjang, maka desa tersebut sudah dinyatakan bukan pelanggan.

Namun saat ingin perpanjang katakan di bulan Maret 2022, dan pelaksana klik tombol perpanjang yang telah disediakan di layanan, ternyata tanggal mulai terhitung sejak 21 oktober 2021 dan kolom tersebut disable.

Dampaknya, pelaksana akan melakukan pesanan baru pada desa tersebut. dengan kata lain, tombol perpanjang tidak ada manfaatnya bagi desa yang sudah lewat masa langganan.

<img width="269" alt="screenshot_560" src="https://user-images.githubusercontent.com/46939846/158281827-48df818a-d824-4d4b-ab29-c36ee96f9459.png">

<img width="700" alt="screenshot_559" src="https://user-images.githubusercontent.com/46939846/158281849-3ae58fab-abb7-402d-a3f6-ae49335a7c71.png">

Disarankan:
1. Kolom tanggal mulai melanjutkan layanan sebelumnya jika desa berada pada kondisi status aktif.
2. Kolom tanggal mulai adalah hari ini, (atau dapat disesuaikan) jika desa berada pada kondisi melampaui masa langganan.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR #58 Kunci langganan https://github.com/OpenSID/Layanan_OpenDESA/pull/58
