### ISSUE TITLE
Sesuaikan Data Kategori Teknis

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#672]
Perlu tambahkan jenis layanan yang saat ini hanya terdapat  : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/a506ff9c-a8ad-4e0f-8993-0cadf05c443b)

1. Layanan Teknis 
2. Layanan Non Teknis

perlu tambahkan : Layanan Teknis Kerja sama 

- [ ] dan selanjutnya perlu sesuaikan data layanan saat ini berdasarkan kategori teknis masing -masing.

untuk daftar list akan segera di lampirkan untuk di sesuaikan datanya.

**Comment by yogiperdana** [comment]
Issue ini cuma menambahkan pilihan select option Layanan Teknis Kerja sama mas @vickyrolanda?

**Comment by vickyrolanda** [comment]
[DATA LAYANAN.xlsx](https://github.com/user-attachments/files/15892151/DATA.LAYANAN.xlsx)
mas @yogiperdana bisa sesuaikan dengan data berikut ini. agar tidak 2 kali kerja mas.

**Comment by yogiperdana** [comment]
ini sesuaikan dari migrasi ya maksudnya mas @vickyrolanda?

**Comment by vickyrolanda** [comment]
> ini sesuaikan dari migrasi ya maksudnya mas @vickyrolanda?

ia mas, supaya sesuai  layanan dan kategorinya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/585
