### ISSUE TITLE
Bug: Tidak dapat Akses Anjungan dan Layanan Pelanggan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#675]
![photo_2024-06-13_16-15-44](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/b4bd8f39-397c-44af-880f-5741315d8bbe)

![Screenshot 2024-06-13 162111](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/c53d31f4-5116-476a-85b7-c004c2e18e57)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/581
