### ISSUE TITLE
Ada Perbedaan Jumlah Layanan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#68]
<img width="960" alt="screenshot_561" src="https://user-images.githubusercontent.com/46939846/158281934-e1a4562d-5bfc-461b-9d73-318add84721e.png">

<img width="960" alt="screenshot_562" src="https://user-images.githubusercontent.com/46939846/158281944-54b5468c-c4ae-4635-bf1c-a0066571d5ad.png">

Gambar di atas menunjukkan ada selisih angka pada Layanan Premium, besar kemungkinan juga akan terjadi di layanan yang lain juga.

Hal tersebut terjadi pada Menu Laporan Layanan dan Layanan Pelanggan.

Setelah diperiksa 1 per 1 (cukup melelahkan karena banyak desa), ada desa yang statusnya belum lunas, sehingga tidak terekam pada Laporan Layanan.

Opsi yang dapat dilakukan:
1. Sediakan menu khusus bagi desa berstatus belum lunas, atau
2. seperti issues sebelumnya, beri tanda khusus pada baris desa yang ada status belum lunas.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/59 yaitu dengan diberi tanda khusus pada baris desa yang ada status belum lunas.
