### ISSUE TITLE
Perjelas Informasi Laporan Kabupaten

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#69]
<img width="960" alt="screenshot_565" src="https://user-images.githubusercontent.com/46939846/158282604-15b1547a-9876-4ca4-b78d-9e9a3628e407.png">

<img width="960" alt="screenshot_562" src="https://user-images.githubusercontent.com/46939846/158282641-4318eeec-0b4a-426f-97af-573b110f68b0.png">

Ketika membuka halaman Laporan kabupaten, ada informasi mengenai Jumlah Pelanggan Premium dan Kolom Bulan ini,
Apakah kolom bulan ini adalah pendaftar pelanggan premium juga?

Jika iya, mengapa jika di jumlah, jumlahnya banyak sekali, jika dibanding dengan yang ada di menu Laporan Layanan maupun Layanan Pelanggan.

Pada halaman 1 saja, jika jumlah bulan ini dihitung sudah 41 belum halaman 2 dan seterusnya, sedangkan di laporan layanan, bulan ini premium hanya 34 desa.

**Comment by FirlianiF** [comment]
Update pak @ariandii , untuk halaman laporan kabupaten ini nnti nya akan diubah menjadi laporan premium yg tujuan utama nya hanya untuk mengetahui jumlah desa yg berlangganan di kabupaten tsb, untuk memudahkan melihat data yang kabupatennya sudah ada 100 desa berlangganan premium, dan untuk fitur lainnya akan dihilangkan karena mengganggu saat validasi perhitungan jumlah desa. untuk laporan bisa dilihat di laporan layanan saja pak.

sudah ada issue terbaru terkait halaman ini:
https://github.com/OpenSID/wiki-layanan-opendesa/issues/121
