### ISSUE TITLE
Bug: Laporan Layanan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#696]
Terjadi error ketika akan membuat laporan layanan.
Replikasi sampai ketemu error:
1. Login ke Layanan
2. Klik Menu Laporan
3. Klik Laporan Layanan 
4. Klik Jumlah Angka pada Kolom Jumlah Pemesanan 

Tampilan Errornya
![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/c2b1c7de-c584-46e3-8428-609f2f9bd632)

![Image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/2b7bae0f-47bd-4d68-ae86-87c9f887a9b0)

**Comment by pandigresik** [comment]
saya coba di local aman

apakah ada user yang bisa saya gunakan untuk test di devlayanan ?

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/ab70633e-8213-439a-8327-07d1aa0ae137)

**Comment by scqolbu24** [comment]
Setelah rilis 2407.0.0 untuk issue ini sudah teratasi atau normal. Sehingga issue ini di tutup.
