### ISSUE TITLE
Bisa simpan bukti pembayaran pemesanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#7]
Di pemesanan pelanggan perlu bisa mengunggah dan menyimpan bukti pembayarannya.
Dan kemudian ada linknya di OpenSID untuk menampilkan.

**Comment by agungsugiarto** [comment]
Bukti pembayaran bisa diunduh, di opensid dan di layanan-opendesa pak ?

**Comment by eddieridwan** [comment]
Ya, seperti faktur.

**Comment by agungsugiarto** [comment]
Commit layanan-opendesa https://github.com/OpenSID/Layanan_OpenDESA/commit/64061d00d788b04ea9b57165cfeafc06c095cdae
PR opensid-premium https://github.com/OpenSID/premium/pull/303

**Comment by eddieridwan** [comment]
@agungsugiarto , di https://layanan.opendesa.or.id belum bisa mengunggah bukti pembayaran?

**Comment by agungsugiarto** [comment]
Bisa pak, ketika membuat pemesanan diwajibkan upload bukti pembayaran,

**Comment by eddieridwan** [comment]
Kalau update mengapa tidak bisa?

**Comment by agungsugiarto** [comment]
Saya disable pak, untuk update

**Comment by eddieridwan** [comment]
Seharusnya bisa. Supaya bisa diunggah atau diubah belakangan. Mohon diaktifkan.

**Comment by eddieridwan** [comment]
@agungsugiarto , alur untuk diterapkan:

1. Pada waktu membuat pemesanan baru, bukti pembayaran boleh dikosongkan kalau status pembayaran belum lunas.
2. Untuk mengubah status pembayaran menjadi lunas, bukti pembayaran harus sudah terunggah.
3. Sebelum lunas, semua kolom isian dapat diubah. Setelah status pembayaran lunas, semua kolom isian terkunci, kecuali bukti pembayaran. 
4. Bukti pembayaran tetap dapat diubah, walaupun status pembayaran telah lunas. Tapi tidak bisa dikosongkan.

**Comment by agungsugiarto** [comment]
Baik pak, akan saya sesuaikan

**Comment by agungsugiarto** [comment]
Sudah saya sesuaikan pak @eddieridwan 

Commit https://github.com/OpenSID/Layanan_OpenDESA/commit/1d959d204b7710f5a44b8161a4b0d470dc89c363
