### ISSUE TITLE
Sesuaikan gambar tanda tangan yang tidak tampil

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#701]
Masuk menu pengurus , lalu klik icon gambar untuk melihat tanda tangan maka tampilannya seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/0b90c37f-f556-4f63-9ee6-cabac8c178db)

Maka perlu di cek apakah direct linknya salah atau perlu direplace dengan images baru.

**Comment by yogiperdana** [comment]
Jika tambah baru fotonya normal. Untuk foto ttd pengurus perlu dicek bersama mas @scqolbu24 di server dan perlu penyesuaian lewat migrasi atau mutator

**Comment by apidong** [comment]
lokasi file ttd ada di 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/20056421/1d7e5aba-fde1-4afe-95c4-d4c97ebc41d3)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/631
