### ISSUE TITLE
Perbaikan error 404 pada halaman details server SiapPakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#702]
silahkan cek di layanan / devlayanan : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/cee3c30d-8663-409f-91fa-c10c7d01dcf0)

- Masuk ke menu Dasboard SiapPakai
- Lalu klik Server
- Lalu klik angka pada kolom jumlah pengguna maka akan muncul tampilan error 404 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/24c160d2-cfe1-4135-b07c-bd8a5a0938f7)

Silahkan cek apakah halaman perlu di sesuaikan ulang atau memang tidak tersedia, jika tidak tersedia bisa disesuaikan dan dibuat daftar pelanggan yang terdata pengguna SiapPakai.

**Comment by yogiperdana** [comment]
Kalau di versi sebelumnya akan tampil seperti apa mas atau mungkin ada link untuk melihat versi layanan lama mas @vickyrolanda

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/619
