### ISSUE TITLE
Perbaikan pada details halaman modul

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#704]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/e11bb9f2-3dc8-406a-ae43-7562dd58f03a)

ada beberapa hal yang perlu dilakukan pada halaman ini : 
- Disable fungsi hapus pada halaman daftar modul dan hanya ijinkan hapus modul versi terakhir saja.
- cek gambar thumbnail yang tidak muncul

**Comment by yogiperdana** [comment]
Untuk letak file sudah sesuai mas @vickyrolanda. Sepertinya memang filenya yang tidak ada. Nanti saya cek dengan mas @scqolbu24

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/630
