### ISSUE TITLE
Bug : Bisa input pembayaran lebih besar dari tagihan yang seharusnya dibayar

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#706]
Langkah - langkah :
Buat pemesanan, jangan lakukan pembayaran 
Lakukan pembayaran beberapa kali, melalui edit pemesanan

Contoh : Pemesanan fitur premium dengan total tagihan 1020000, kemudian lakukan pembayaran beberapa kali
pembayaran pertama 500000 lalu simpan
pembayaran kedua 400000 lalu simpan
pembayaran ketiga 500000 lalu simpan

[Screencast from 04-07-24 13:34:04.webm](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/38535c73-a71a-46be-a57c-86c16d1531ff)

Sekali pembayaran ketika buat pemesanan juga bisa input pembayaran > tagihan

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/6933cdd8-4aa3-4a53-a12f-a06afdac92dd)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/618
