### ISSUE TITLE
Format penulisan angka tidak seragam pada menu pemesanan

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#707]
Langkah - langkah : 
Buat pemesanan, pilih salah satu layanan perhatikan format pada total (menggunakan pemisah . untuk ribuan) berbeda dengan format pada inputan uang lainnya ( menggunakan pemisah , untuk ribuan )

[Screencast from 05-07-24 09:22:43.webm](https://github.com/OpenSID/wiki-layanan-opendesa/assets/1853475/ea632526-7932-49d3-8795-4b81ede5b12c)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/618
