### ISSUE TITLE
tambahkan cetak faktur sesuai yang dibayarkan pada pemesanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#710]
Saat ini pembayaran dapat dilakukan bertahap melalui pemesanan, namun fungsi cetak faktur masih tersedia cetak faktur sesuai dengan tagihan saja. seperti contoh berikut ini : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/b133abe8-6364-4848-8ee1-e30914e0ceaa)

Hasilnya : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/5a2fee50-9673-4d68-af9d-62c945914d46)

Padahal pembayaran dilakukan 2 kali dengan tanggal yang berbeda : 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/41fb680e-c0d8-4819-bf1d-ae0da93b15c5)

solusi yang perlu dipertapkan adalah : 
1. Cetak faktur saat ini perlu disesuaikan pada halaman pemesanan agar dapat mencetak 1 faktur tersendiri berdasarkan yang di bayar. 

![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/0d244ce5-56b5-4ec3-87ab-4e09760319b1)

tambahkan icon cetak faktur di details pemesanan diatas agar faktur dapat di cetak berdasarkan pembayaran saja.

**Comment by pandigresik** [comment]
Bentuk fakturnya seperti apa nantinya ? 
Dimana diletakkan jumlah bayarnya ?

Tampilan sekarang detail pemesanan yang ditampilkan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/627
