### ISSUE TITLE
Perbaiki jenis layanan pada saat proses batalkan pemesanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#716]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/ae785619-c050-4169-b8ac-dc5ebdba9bcc)

saat lakukan proses batalkan pemesanan ada terjadi kekurangan seperti berikut ini : 
1. Pilih pesanan yang bisa di batalkan lalu klik batalkan 
2. lalu lihat layanan yang di pesan tidak terselect
3. lalu setelah data batal di submit 
4. maka status berhasil dan statusnya sudah berubah menjadi dibatalkan 
5. lalu klik lagi button proses dan klik perbaharui
6. maka akan muncul error seperti berikut ini : 
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/59082428/d8a1fd4c-134c-4f64-9f26-e7d43efa45a7)

**Comment by pandigresik** [comment]
Kemungkinan salah satu efek layanan yang sudah dihapus

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/628
