### ISSUE TITLE
Batasin tombol hapus pada pemesanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#717]
- [ ] Tambahkan logika untuk tombol hapus pada pemesanan hanya jika pemesanan belum dilakukan pembayaran saja, jika sudah upload pembayaran dan sudah ada pemabayaran maka pemesanan tidak dapat di hapus, dan hanya dapat dilakukan dengan cara membatalkan pemesanan.

- [ ] dan jika status sudah dibatalkan maka tombol hapus tidak lagi tersedia.

case ini untuk mengantisipasi agar jika pengguna sudah lakukan trf dan dilakukan pengembalian dana maka pemesanan tetap harus di buat namun dilakukan pembatalan agar dilaporan layanan tercatat ada pemesanan yang di batalkan.

**Comment by yogiperdana** [comment]
![image](https://github.com/OpenSID/wiki-layanan-opendesa/assets/14155050/093bcb2d-ee1f-4965-9040-e8c8fe81ef30)

Maksudnya tombol aksi yang warna merah itu bukan mas @vickyrolanda ?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/632
