### ISSUE TITLE
Buatkan Informasi jika domain berbeda pada saat pembuatan pemesanan Dasbor SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#718]
Saat ini baru ada notifikasi bahwa domain perlu diarahkan ke server siapapkai, perlu juga informasi terkait domain yang diarahkan di data pelanggan berbeda.
![photo_2024-07-08_16-03-37](https://github.com/OpenSID/wiki-layanan-opendesa/assets/68048807/7edc44cf-fc9f-4ed1-96e5-a2fd2bcf6d57)

Pada kasus ini domain yang didaftarkan di pelanggan adalah desa.id sedangkan yang sudah mengarah ke server siappakai menggunakan domain yang lain.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/639
