### ISSUE TITLE
Bug: Nama Desa Pelanggan dengan detail pemesanan berbeda

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-layanan-opendesa#723]
pada pelanggan tertulis `kedunganayar`
![image](https://github.com/user-attachments/assets/b1d6492d-db5d-4f9c-bf75-4eb91ed0f326)

pada detail pemesanan tertulis `Guranganyar`
![image](https://github.com/user-attachments/assets/9d4dc0ac-5389-4e49-be0b-4d8a3553299a)

seharusnya yang benar adalah Kedunganyar.

Jika di cek database dikarenakan ada perubahan nama desa
![image](https://github.com/user-attachments/assets/6eaea7a2-0dfa-49b2-9acb-4a72c48e3e39)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/634
