### ISSUE TITLE
Token tidak terupdate ketika perpanjangan OpenSID

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#727]
![image](https://github.com/user-attachments/assets/095dae4f-e1cf-44a7-8f52-a1b7c1bfad53)

![image](https://github.com/user-attachments/assets/51571719-3a42-424c-99dd-c1ba2339e6af)
diliat di menu pelanggan, tgl akhirnya gk update padahal perpanjangan juga sudah lunas. 

cek untuk desa ini  : 
![image](https://github.com/user-attachments/assets/783b22fe-f9c1-43de-b4a0-70ab2651ec52)

yang perlu di cek adalah kenapa desa diatas tidak mengikuti tanggal perpanjangan pada layanan sehinga layanannya bisa update.

**Comment by yogiperdana** [comment]
Harusnya tanggal akhir jadi berapa mas @vickyrolanda

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/647
