### ISSUE TITLE
Cek terkait laporan layanan yang tidak tampil pada tahun 2022

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#728]
![image](https://github.com/user-attachments/assets/79537c68-89b7-4e6e-8b23-97137e409c39)

dilihat dari laporan pemesanan di bulan tertentu pada tahun 2022 maka hasilnya hanya sedikit dan bahkan ada yang tidak ada pemesanan , hal ini perlu di cek apakah ada kesalahan pada data atau memang di database memang tidak tersedia pemesanan pada tahun 2022 dengan bulan tertentu & tanggal tertentu.

**Comment by yogiperdana** [comment]
kalau di prod layanan aman mas datanya ada 878. Tapi memang tidak semua data di 2022 dan 2021 terecord karena kolom tanggal nota dan pembayaran sendiiri adanya baru dari agustus 2022

![image](https://github.com/user-attachments/assets/9d2391ed-f9f5-4493-ab44-c82412905c8a)

**Comment by yogiperdana** [comment]
Saya buat siap review karena data di database memang demikian sesuai keterangan di atas

**Comment by vickyrolanda** [comment]
mas @yogiperdana apakah bisa dibuatkan migrasi agar kolom yang kosong dan tidak ada mengikuti tanggal mulai layanan agar pada laporan bisa dapat terhitung keseluruhannya, karena ini akan menyangkut laporan keseluruhannya nanti.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/668
