### ISSUE TITLE
Error datatables di menu Daftar Hitam

### ISSUE THREAD

**Issue by roaddee** [OpenSID/wiki-layanan-opendesa#73]
Error saat akses daftar hitam

![image](https://user-images.githubusercontent.com/45786885/159290561-9552d346-3cf2-49d7-a1c4-2b741b01a44e.png)

**Comment by roaddee** [comment]
cc : @FirlianiF

**Comment by FirlianiF** [comment]
> cc : @FirlianiF

Noted Pak

**Comment by FirlianiF** [comment]
Format yang dikirim dari opensid berupa titik, sedangkan di simpan titik nya tidak ada. dan ada yang double titik.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/62
