### ISSUE TITLE
Perbaikan antara invoice melalui cetak & klik faktur berbeda

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#738]
Ada perbedaan antara bentuk faktur melalui cetak faktur dengan melalui Klik faktur melalu halaman semua pemesanan berikut tampilan yang berbeda : 

Tampilan invoice melalui cetak invoice : 
![image](https://github.com/user-attachments/assets/4319f419-999a-444f-8bbb-21348b80641d)

Tampilan invoice melalui klik faktur : 
![image](https://github.com/user-attachments/assets/1c4adb13-8952-4002-9606-32420d990acc)

cara replikasinya : 
1. masuk ke halaman semua pemesanan
2. pilih desa klik pada ceklist sebelah kiri
3. klik tombol cetak faktur di bagian atas 
![image](https://github.com/user-attachments/assets/90099551-96f5-4f2d-8362-e003032f3e9f)

cara replikasi yang ke2 : 
1. Buka halaman semua pemesanan
2. lalu lihat bagian data tabel ke kolom faktur
3. Klik link faktur 

dari 2 cara diatas perbandingannya adalah invoce yang diatas.

**Comment by pandigresik** [comment]
Yang benar yang mana ? pakai pajak atau tidak pada invoicenya. Nilai tagihannya juga beda karena dipengaruhi pajak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/662
