### ISSUE TITLE
Laporan pelanggan install & update masih belum relevan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#743]
Jika di cek dari halaman pelanggan maka terdapat informasi block kuning yang menyatakan bahwa ada pelanggan dengan layanan install & update namun setiap ada rilis baru ini akan memeriksa apakah desa tersebut sudah di update apa belum. 

namun saat ini laporannya masih belum relevan lihat gambar dibawah ini : 
![image](https://github.com/user-attachments/assets/82bb03fd-fb14-4e1b-83f8-325e0ea91bf8)

dilayanan desa tersebut masih terbaca versi 2408.0.0 
![image](https://github.com/user-attachments/assets/6b878a90-f189-4e3f-b90d-a403f697c899)

Padahal jika di cek ke halaman langsung versi sudah terupdate : 
![image](https://github.com/user-attachments/assets/b8049951-7c5f-48fb-8a60-fd4cbb832138)

**Comment by pandigresik** [comment]
Dari sisi laporan sudah sesuai, karena masih tercatat 2408.0.0 sedangkan versi terakhir adalah 2408.0.3.
Jadi yang perlu dicek adalah fitur catat-versi yang dikirim oleh OpenSID dan diterima oleh layanan

**Comment by pandigresik** [comment]
Sudah dikerjakan pada PR https://github.com/OpenSID/premium/pull/4028
