### ISSUE TITLE
Hasil excel pada fitur kerjasama tidak mengikuti filter 

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#744]
Pilih Pelanggan - Kerjasama
Lakukan filter salah satu desa
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter  

[Screencast from 23-08-24 15:35:49.webm](https://github.com/user-attachments/assets/b7c6534b-3a8b-4a3e-b65d-ca1165156600)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/676
