### ISSUE TITLE
Hasil excel pada fitur pemesanan tidak mengikuti filter

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#745]
Pilih Pemesanan - Semua Pemesanan
Lakukan filter salah satu desa
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 23-08-24 15:58:02.webm](https://github.com/user-attachments/assets/c624eb1c-d2b0-4ef2-ad3a-9693dba59d83)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/677
