### ISSUE TITLE
Hasil excel pada fitur pelanggan tidak mengikuti filter 

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#748]
Pilih Pelanggan - Pelanggan
Lakukan filter salah satu desa
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 28-08-24 08:27:14.webm](https://github.com/user-attachments/assets/cc6c3d3c-8a32-429b-86fd-43032bae249f)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/679
