### ISSUE TITLE
Hasil excel pada fitur laporan layanan tidak mengikuti filter 

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#750]
Pilih Laporan - Laporan Layanan
Lakukan filter salah satu nama layaan
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 28-08-24 09:35:01.webm](https://github.com/user-attachments/assets/d87e87c4-0b25-4207-8b78-291efa1f0465)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/681
