### ISSUE TITLE
Hasil excel pada fitur laporan pelaksanan tidak mengikuti filter

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#751]
Pilih Laporan - Laporan Pelaksana
Lakukan filter salah satu nama 
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 28-08-24 10:35:33.webm](https://github.com/user-attachments/assets/335248e5-3d61-4105-80cc-db392e9faf76)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/682
