### ISSUE TITLE
Hasil excel pada fitur laporan PPH tidak mengikuti filter

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#752]
Pilih Laporan - Laporan PPH
Lakukan filter salah satu nama
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 28-08-24 10:58:38.webm](https://github.com/user-attachments/assets/c9e5376d-508b-4101-bdf4-b7eb963d4552)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/683
