### ISSUE TITLE
Hasil excel pada fitur laporan bagi hasil pelaksana tidak mengikuti filter

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-layanan-opendesa#753]
Pilih Laporan - Laporan Bagi HasilPelaksana
Lakukan filter salah satu nama
Klik tombol excel
Buka hasil download, ternyata hasilnya tidak sesuai dengan filter

[Screencast from 28-08-24 11:09:09.webm](https://github.com/user-attachments/assets/0acb271d-37f2-4170-8bc3-c91548ec6ff2)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/684
