### ISSUE TITLE
Sesuaikan tanggal mulai perpanjangan layanan  dengan tanggal sebelumnya berlangganan.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#759]
![image](https://github.com/user-attachments/assets/da271a49-e9df-4d12-a5ce-a4f42143945c)

saat lakukan perpanjangan layanan tanggal mulai pesanan selalui diambil dengan tanggal terkini atau saat ini, seharusnya tanggal yang diambil adalah tanggal layanan sebelumnya sehingga awal mulai layanan selalui menjadi trigger tanggal mulai pada perpanjangan selanjutnya. 

pepanjangan layanan bukan seperti buat pesanan baru yang tanggal mulai selalu berdasarkan tanggal mulai berlangganan tetapi harus mengikuti tanggal mulai pada pemesanan layanan sebelumnya yang sudah expired.

**Comment by pandigresik** [comment]
mas @vickyrolanda 
pesanan lama tgl awal 2022-01-01, tgl akhir 2023-01-01
perpanjangan menjadi 
tgl awal 2022-01-01, tgl akhir 2024-01-01 ataukah 
tgl awal 2023-01-02, tgl akhir 2024-01-01

**Comment by pandigresik** [comment]
sebenarnya mau perpanjangan maupun pesanan baru itu sama saja, yang beda hanya cara pengisian saja dimana ketika perpanjangan data default telah terisi

**Comment by vickyrolanda** [comment]
Kalo sy coba dari perpanjangan tanggal yang terisi tgl saat ini mas, melalui halaman pemesanan lalu klik perpanjangan yg muncul tanggal saat ini.

**Comment by pandigresik** [comment]
> Kalo sy coba dari perpanjangan tanggal yang terisi tgl saat ini mas, melalui halaman pemesanan lalu klik perpanjangan yg muncul tanggal saat ini.

apakah seharusnya berisi tgl akhir + 1 ? 
jadi misal pesanan awal 2022-01-01 sd 2022-12-31, ketika perpanjangan apakah menjadi 
a. 2022-01-01 sd 2023-12-31 ( diatas diterangkan trigger dari tanggal awal pesanan lama)
b. 2023-01-01 sd 2023-12-31

yang benar yang A atau B ?

**Comment by pandigresik** [comment]
> Kalo sy coba dari perpanjangan tanggal yang terisi tgl saat ini mas, melalui halaman pemesanan lalu klik perpanjangan yg muncul tanggal saat ini.

Saya coba tanggal mulai sudah mengikuti tanggal berakhir layanan sebelumnya, jadi ini sudah sesuai

[Screencast from 17-09-24 09:13:23.webm](https://github.com/user-attachments/assets/9d203ef3-55e6-4c19-aa0e-f046c8309071)

**Comment by vickyrolanda** [comment]
sesuai pemeriksaan dengan mas afandi issue ini sudah diatasindan tidak terjadi lagi pada layanan
