### ISSUE TITLE
Permintaan fitur: Ubah Urutan pada Tabel Rincian Pemesanan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#76]
### Apa kekurangan yg ingin diatasi?

Saat ini pemesanan akhir berada pada urutan bawah.

Jika desa pesan layanan sudah banyak, akan terus kebawah.

<img width="957" alt="screenshot_57" src="https://user-images.githubusercontent.com/46939846/160449545-37f2d3fb-0584-40e9-95d5-4820a3b7f524.png">

### Jelaskan solusi yg diinginkan

Usul untuk pesanan layanan terakhir agar dibalik menjadi urutan nomor 1.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Semua

**Comment by andifahruddinakas** [comment]
Disesuaikan di API layanan

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/63
