### ISSUE TITLE
Sesuaikan kondisi pembelian lisensi anjungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#760]
Ketentuan lisensi anjungan sbb:

1. Pembelian lisensi anjungan hanya dapat dilakukan oleh pelanggan Premium. Supaya memastikan menggunakan versi terbaru OpenSID dan anjungan
2. Jika langganan Premium berakhir dan tidak diperpanjang, lisensi anjungan dapat terus digunakan. Tetapi tidak dapat di-update. Yaitu akan terkunci pada versi OpenSID tersebut sampai versi tersebut menjadi rilis Umum.
3. Setelah itu, lisensi anjungan tersebut dapat terus digunakan meski OpenSID di-update ke rilis Umum terbaru.

**Comment by pandigresik** [comment]
> Ketentuan lisensi anjungan sbb:
> 
> 1. Pembelian lisensi anjungan hanya dapat dilakukan oleh pelanggan Premium. Supaya memastikan menggunakan versi terbaru OpenSID dan anjungan
> 2. Jika langganan Premium berakhir dan tidak diperpanjang, lisensi anjungan dapat terus digunakan. Tetapi tidak dapat di-update. Yaitu akan terkunci pada versi OpenSID tersebut sampai versi tersebut menjadi rilis Umum.
> 3. Setelah itu, lisensi anjungan tersebut dapat terus digunakan meski OpenSID di-update ke rilis Umum terbaru.

point 2 dan 3 sepertinya lebih cocok issue di OpenSID

**Comment by andifahruddinakas** [comment]
> > Ketentuan lisensi anjungan sbb:
> > 
> > 1. Pembelian lisensi anjungan hanya dapat dilakukan oleh pelanggan Premium. Supaya memastikan menggunakan versi terbaru OpenSID dan anjungan
> > 2. Jika langganan Premium berakhir dan tidak diperpanjang, lisensi anjungan dapat terus digunakan. Tetapi tidak dapat di-update. Yaitu akan terkunci pada versi OpenSID tersebut sampai versi tersebut menjadi rilis Umum.
> > 3. Setelah itu, lisensi anjungan tersebut dapat terus digunakan meski OpenSID di-update ke rilis Umum terbaru.
> 
> point 2 dan 3 sepertinya lebih cocok issue di OpenSID

Sudah lama diterapkan, sepertinya perubahan dilayanan terkait token mempengaruhi isi token terkait anjungan ini. Di OpenSID yang menerima validasi akhir, apakah pernah memesan anjungan atau tidak. Untuk mengurangi dampak perubahan script pada OpenSID.

**Comment by vickyrolanda** [comment]
Testing : 
1. Pastikan saat pemesanan 
2. Ketika ganti domain 
3. Ketika ada lisensi anjungan jika tidak ada premium pastikan tidak bisa jalan di OpenSID 
4. Pastika premium sudah kadaluarsa anjungan tetap bisa jalan
5. Harus mengajak pengguna melakukan testing misalkan dengan (Bung Muhammad -larang selatan)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/696
