### ISSUE TITLE
Bug/error: terapkan ketentuan anjungan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#761]
### Jelaskan error yg dialami

Saat ini penggunaan anjungan tidak sesuai dengan ketentuan lisensi anjungan. Setelah lisensi anjungan diperoleh seharusnya dapat digunakan terus meskipun sudah tidak berlangganan Premium lagi. 

### Cara untuk mereplikasi errornya

Banyak keluhan pengguna, di mana setelah Premium berakhir, anjungan tidak dapat digunakan lagi.

### Hasil yg diharapkan

Terapkan sesuai dengan ketentuan lisensi anjungan.

Ketentuan lisensi anjungan sbb:

1. Pembelian lisensi anjungan hanya dapat dilakukan oleh pelanggan Premium. Supaya memastikan menggunakan versi terbaru OpenSID dan anjungan
2. Jika langganan Premium berakhir dan tidak diperpanjang, lisensi anjungan dapat terus digunakan. Tetapi tidak dapat di-update. Yaitu akan terkunci pada versi OpenSID tersebut sampai versi tersebut menjadi rilis Umum.
3. Setelah itu, lisensi anjungan tersebut dapat terus digunakan meski OpenSID di-update ke rilis Umum terbaru.

### Tangkapan layar dan log error

n/a

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

versi Premium yg tidak diperpanjang. 

### Informasi tambahan

Perbaikan ini perlu diprioritaskan, karena menyebabkan keresahan pengguna, yg telah mengeluarkan dana 750rb untuk lisensi anjungan dengan ekspektasi dapat digunakan terus.

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, contoh desa wadeng, pernah beli anjungan (termasuk licensenya) dan sudah tidak perpanjang
![image](https://github.com/user-attachments/assets/2ab16e19-f490-4be4-b56d-f7f3c67f49c0)
![image](https://github.com/user-attachments/assets/9497bd5f-ed5d-459b-9217-742fcaac81ee)

namun dilihat dari isi tokennya:
tidak ada data terkait pembacaan license anjungan
![image](https://github.com/user-attachments/assets/144681ad-3328-480a-b61f-86fe854766c9)
harusnya ada seperti ini
![image](https://github.com/user-attachments/assets/7e0a774d-7266-4033-8fac-9877aeb98702)

Catatan:
- Sekalian buat nilai variabel true dan false aja, jgn seperti sebelumnya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/696
