### ISSUE TITLE
Tambahkan keterangan PPn dibayarkan Oleh pengguna pada invoice

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-layanan-opendesa#764]
Sesuai kebutuhan layanan dimana opendesa merupakan PTKP sehingga tidak bisa menerbitkan faktur pajaknya.
maka perlu ditambahkan keterangan seperti berikut ini "**Invoice ini tidak termasuk PPN maka untuk melakukan pembayaran PPN dapat dilakukan pembayar oleh pengguna sendiri**"
![image](https://github.com/user-attachments/assets/9c8b755b-1cda-4e5d-9186-19ece1662d66)

- [ ] pastikan penerapan juga dilakukan pada invoice yang dikirim ke OpenSID 
- [ ] pastikan penerapan dilakukan secara konsisten pada beberapa cara generate invoice

**Comment by apidong** [comment]
> Sesuai kebutuhan layanan dimana opendesa merupakan PTKP sehingga tidak bisa menerbitkan faktur pajaknya. maka perlu ditambahkan keterangan seperti berikut ini "**Invoice ini tidak termasuk PPN maka untuk melakukan pembayaran PPN dapat dilakukan pembayar oleh pengguna sendiri**" ![image](https://private-user-images.githubusercontent.com/59082428/369732878-9c8b755b-1cda-4e5d-9186-19ece1662d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzk4NzIsIm5iZiI6MTcyNzA3OTU3MiwicGF0aCI6Ii81OTA4MjQyOC8zNjk3MzI4NzgtOWM4Yjc1NWItMWNkYS00ZTVkLTkxODYtMTllY2UxNjYyZDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4MTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjg0ZTNjMmEwYzMxYzM4MDcwMjI3NWZjOGUwODJjOGRiNzViOTAxMmRkMmQ3M2NlMGEyYTI0MzA2MTM2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.82s0M3_PA-P2W4Z3yN_SfID4n56kmECaXGS7NDn-oKQ)
> 
> * [ ]  pastikan penerapan juga dilakukan pada invoice yang dikirim ke OpenSID
> * [ ]  pastikan penerapan dilakukan secara konsisten pada beberapa cara generate invoice

perlu juga di tanyakan juga apakah ini untuk semua invoice. karena pengguna kadang mengirimkan hanya pembayaran  1jt dan ada juga yang mengirimkan pembayaran 1.020.000.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/700
