### ISSUE TITLE
Tambahkan infrormasi kategori pada /api/v1/pelanggan/pemesanan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-layanan-opendesa#77]
Berkaitan dengan issue https://github.com/OpenSID/OpenSID/issues/5098

Akan digunakan untuk menampilkan informasi pengguna berdasarkan kategori layanan yang diambil, misalnya notifikasi install/update per tgl 1.

**Comment by FirlianiF** [comment]
Kategori layanan sudah tersedia pada folder desa > cache > file status_langganan, lengkap dengan detail layanan nya dengan format seperti dibawah ini.
{"id":"1","kategori_id":"3","jenis":"1","nama":"Hosting 1 Gb","harga":"200000.00","deskripsi":"Layanan Hosting 1 Gb","created_at":"2021-06-22 21:41:54","updated_at":"2022-03-31 23:49:51","ketentuan":"-"}

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/177
