### ISSUE TITLE
Matikan semua data yang tertera di faktur yang sudah di terbitkan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#78]
pada faktur pemesanan, saat ini data layanan yang dimatikan/dibekukan hanya harga saja.

Tolong matikan semua data yang ada pada faktur yg telah diterbitkan, agar jika ada perubahan pada layanan, faktur yang telah terbit tidak terpengaruh oleh perubahan tersebut.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/61
