### ISSUE TITLE
Sesuaikan Tampilan Info di Layanan dan OpenSID

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#79]
Saat ini, tampilan keterangan setiap layanan berbeda dengan yang ada di layanan dan di opensid. berikut gambar perbedaannya:

<img width="960" alt="screenshot_123" src="https://user-images.githubusercontent.com/46939846/161049358-910d0d86-21d1-4947-91dc-f43f54ac8e1c.png">

**Comment by FirlianiF** [comment]
![Capture-info-layanan-opensid](https://user-images.githubusercontent.com/30171560/162061231-3e96174d-b8b7-4257-a2ee-50cb886dd172.PNG)
 Terlampir tampilan info layanan di OpenSID, mohon penjelasan perbedaan nya ada di sebelah mana ya pak @ariandii ?

**Comment by ariandii** [comment]
![Uploading IMG_20220407_070727.jpg…]()

**Comment by ariandii** [comment]
![IMG_20220407_070727](https://user-images.githubusercontent.com/46939846/162094939-70f2de00-a251-478e-845a-d91ee806a8dc.jpg)

**Comment by ariandii** [comment]
ini di berputar pagi ini barusan saya lihat juga berantakan.

![Screenshot_2022-04-07-07-25-42-23_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/162096400-4617391f-6e5f-49db-83c2-d2ffccb4846c.jpg)

**Comment by FirlianiF** [comment]
![berputar-capt](https://user-images.githubusercontent.com/30171560/162106064-e1427dd7-27d5-4735-9cbf-d6f3b1f49b2e.PNG)
Terlampir yang berputar pak, tampilannya normal, itu dikarenakan cache nya pak.

**Comment by FirlianiF** [comment]
Mohon untuk dihapus terlebih dahulu cache nya yang ada di folder desa > cache > status_langganan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1038
