### ISSUE TITLE
Tampilkan jumlah pemesanan per pelanggan dan tampilkan daftar pemesanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#8]
Di daftar pelanggan, tampilkan kolom menunjukkan jumlah pemesanan. Klik angka tersebut untuk menampilkan pemesanan pelanggan tsb di halaman pemesanan.

Sediakan fitur untuk mengurut daftar pelanggan menurut jumlah pemesanan.

**Comment by agungsugiarto** [comment]
Sudah di master melalui commit https://github.com/OpenSID/Layanan_OpenDESA/commit/42468394ab0e7a09c890da405223d34e4e71dbe0
