### ISSUE TITLE
Tabel Status Langganan Belum Sesuai

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#82]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/163594917-aaab64d2-ae09-41b4-933f-f42a92f6c841.png">

Walau sudah pilih Tidak Aktif Langganan, tetapi yg muncul di tabel adalah yang aktif dan Terdaftar, tidak aktif, menunggu verifikasi, dll.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/64
