### ISSUE TITLE
Tabel Baru Berakhir Belum Sesuai

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#83]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/163595131-3f022a22-c6b4-44d9-9baa-5e1efe8a1063.png">

Problem sama dengan issues #82

**Comment by eddieridwan** [comment]
@ariandii @FirlianiF : 

Sepertinya salah satu penyebab adalah adanya beberapa pemesanan, termasuk di mana ada pesanan yg seharusnya tidak dihitung lagi. Misalnya, kalau desa sudah memperpanjang langganan premium, maka pesanan premium yg lama tidak diperhitungkan lagi. Contoh https://layanan.opendesa.id/layanan/pemesanan?pelanggan_id=584

Perhatikan juga bahwa pemesanan yg tidak memiliki masa langganan, seperti 'tema', tidak berlaku untuk filter yg bersifat waktu -- karena tidak relevan. Jadi untuk filter 'baru berakhir', layanan seperti 'tema' tidak diikutsertakan. Seharusnya layanan seperti 'tema' hanya relevan bagi filter 'aktif' saja. 

Dalam membuat solusi untuk masalah ini, mohon juga perhatikan kasus di mana suatu desa pelanggan berlangganan beberapa layanan, misalnya: hosting, premium, install/update. Apa yg seharusnya ditampilkan pada `Status Langganan`, jika di filter tidak membatasi pada jenis layanan tertentu (seperti halnya di filter di contoh di atas)? 

Kalau semua layanan tersebut mempunyai masa langganan yg sama, tidak masalah. Tetapi bagaimana dengan kasus di mana masing2 masa langganannya berbeda? Jadi bagaimana dengan kasus di mana salah satu langganan sesuai dengan filter (dalam contoh: baru berakhir), tapi ada langganan yg lain yg statusnya berbeda, misalnya masih aktif?

Mungkin solusinya:

1. tampilkan `Status Langganan` sesuai dengan filter (misalnya dalam contoh filter 'baru berakhir', tampilkan status 'tidak aktif')
2. jika pelanggan tersebut juga memiliki langganan lain dengan status berbeda, tampilkan suatu indikator (misalnya tanda '*') yang menunjukkan hal tersebut
3. indikator tersebut dapat diklik dan bersifat seperti `Jumlah Pemesanan`, yaitu menampilkan pesanan bagi desa tersebut.

**Comment by eddieridwan** [comment]
@FirlianiF , karena masalah ini cukup rumit, buat dokumentasi aturannya dulu secara rinci, sebelum menerapkan solusinya. Hal ini perlu dilakukan sebelum menerapkan solusi untuk semua issue terkait filter pelanggan.

**Comment by eddieridwan** [comment]
Untuk mengurangi kebingungan, sebaiknya pelaksana selalu memilih jenis layanan yg akan difilter. Dengan demikian, Status Langganan akan jelas bagi jenis layanan ybs. @FirlianiF Nanti setelah anda temukan solusinya, mohon tambahkan penjelasan pengertian fitur filter Pelanggan ini, dan juga jelaskan caranya untuk mengurangi kebingungan. 

Sebenarnya, salah satu strategi adalah dengan mengharuskan dipilihnya Jenis Layanan tertentu. Karena biasanya pelaksana mencari informasi mengenai:

1. status pelanggan untuk Jenis Layanan tertentu, misalnya hosting; dan **bukan**

2. status pelanggan untuk Jenis Layanan manapun (misalnya tampilkan semua pelanggan yg saat ini memiliki langganan yg baru berakhir, entah itu hosting, premium, atau lainnya) . Walaupun secara teoritis bermakna, secara praktis mungkin kurang bermanfaat.

Strategi mengharuskan Jenis Layanan diisi akan sama sekali menghindari kerumitan di atas, di mana solusinya perlu mempertimbangkan status dari berbagai jenis layanan.

Ok, @FirlianiF , mohon buat solusi dengan mengharuskan Jenis Layanan diisi untuk filter Pelanggan berdasarkan Status Pelanggan.

Jika Jenis Layanan diisi lebih dari satu layanan, misalnya 'hosting, premium', maka Status Langganan yg berlaku hanya 'aktif'. Dan diartikan sebagai berikut:

'tampilkan semua pelanggan yg memiliki layanan hosting **dan** premium yang aktif'

Yaitu dalam hal Jenis Layanan disii lebih dari satu layanan, semua jenis filter Status Langganan selain 'aktif' tidak berlaku dan dihilangkan.

**Comment by FirlianiF** [comment]
Status langganan pada tabel tersebut merupakan Status Pendaftaran Pelanggan, akan saya rapihkan agar informasi nya jelas dan tidak membingungkan.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/148
