### ISSUE TITLE
Tabel Sudah Berakhir Belum Sesuai

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#84]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/163595257-15e1b695-e05d-4401-bd90-5d0b5229b051.png">

Problem sama dengan issue #82

**Comment by FirlianiF** [comment]
Status langganan pada tabel tersebut merupakan Status Pendaftaran Pelanggan, akan saya rapihkan agar informasi nya jelas dan tidak membingungkan.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/148
