### ISSUE TITLE
Tampilkan faktur di OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#9]
Di OpenSID, tampilkan faktur di daftar pemesanan seperti tercetak di Layanan. Tidak seperti daftar layanan yg ada sekarang.

**Comment by agungsugiarto** [comment]
Commit layanan-opendesa https://github.com/OpenSID/Layanan_OpenDESA/commit/ab73697b86cd1dc58add130ec6861b5b41774365
PR opennsid-premium https://github.com/OpenSID/premium/pull/302

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/302.
