### ISSUE TITLE
Kirim pesan langganan SaaS akan berakhir

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#90]
Secara otomatis deteksi pelanggan SaaS yg masa langganannya akan berakhir.

Jika akan berakhir, lakukan sebagai berikut:

1. kirim peringatan pada hari 21, 14, 7, 1 sebelum masa langganan berakhir ke alamat email dan Telegram kontak site ybs

Catatan:

- alternatifnya, peringatan bisa dikirim oleh Layanan; jika dilakukan Layanan, Dashboard SaaS tidak perlu menyimpan kontak site,

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/73 (masih manual)

**Comment by scqolbu24** [comment]
berdasarkan pertemuan 16 Juni 2022, email yang digunakan diambil dari table user, sehingga issue ini sudah bisa di close.
