### ISSUE TITLE
Panggil Dashboard SaaS dari Layanan untuk pelanggan SaaS baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-layanan-opendesa#92]
Setelah langganan SaaS baru difinalkan, panggil Dashboard SaaS untuk menyiapkan site OpenSID SaaS. Sebelum itu, pelaksana perlu memilih server SaaS mana yg akan digunakan.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/71
