### ISSUE TITLE
Agar Pilihan Layanan Sesuai Abjad

### ISSUE THREAD

**Issue by ariandii** [OpenSID/wiki-layanan-opendesa#98]
Saat ini, pada pilihan layanan masih belum urut (atau urut berdasarkan ID).

Untuk mempermudah pencarian, dapat diurutkan berdasarkan Abjad Nama Layanan tersebut.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/170720264-361865ed-beac-40e0-85c6-eed8bc8404f6.png">

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/144
