### ISSUE TITLE
Tambah Pelanggan Selain Desa (Mitra)

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-layanan-opendesa#99]
Saat ini yang memesan layanan dari OpenDesa tidak hanya Desa tapi juga pihak Ketiga seperti badan usaha, khususnya anjungan desa mandiri. olehnya perlu dibuatkan fitur menambahkan pelanggan selain desa. dan faktur pelanggan untuk non desa tidak dikirim ke desa.

**Comment by eddieridwan** [comment]
@FirlianiF , permintaan ini terkait pemesanan yg dilakukan oleh mitra OpenDesa (melalui Divisi Komersial). Sebagai contoh, mitra pemasaran anjungan atau mitra yg produksi anjungan. Dalam hal ini, mitra langsung menjual kepada desa, dan sebagian mitra diperbolehkan menjual dengan harga yg berbeda dengan harga resmi OpenDesa.

Dengan demikian, faktur yg diterima desa adalah yg dibuat oleh mitra ybs dan bukan faktur yg diterbitkan oleh aplikasi Layanan. Yaitu, dalam kasus seperti ini, faktur tidak diterbitkan oleh aplikasi Layanan, dan tidak ditampilkan di aplikasi OpenSID untuk pemesanan ybs. 

Untuk solusinya, diperlukan unsur sbb:

1. mencatat daftar mitra yg resmi. Yaitu fitur ini tidak berlaku untuk pihak ketiga selain mitra yg terdaftar di Layanan. Untuk masing2 mitra catat: nama mitra, alamat mitra NPWP, kontak (nama, nomor HP, email, Telegram), status (aktif/tidak aktif)
2. pada watku pelaksana memasukkan data pemesanan, pelaksana dapat memilih salah satu mitra terdaftar yg aktif sebagai pihak penjualnya
3. jika pada (2) mitra penjual terisi, maka faktur tidak diterbitkan di Layanan
4. jika pada (2) mitra penjual terisi, di OpenSID faktur Layanan tidak ditampilkan. Sebagai penggantinya tampilkan penjelasan bahwa faktur dapat diperoleh dari mitra -- tampilkan nama dan alamat mitra.
5. nilai pemesanan yg dicatat di Layanan tetap menggunakan harga standar bagi layanan ybs, mis untuk anjungan

Perhatikan bahwa pemesanan yg dijual oleh mitra tetap perlu dimasukkan ke Layanan, untuk memperoleh token yg diperlukan - termasuk untuk anjungan (ada issue terpisah untuk ini). 

Perhatikan bahwa pelanggan tetap desa, karena token akan selalu diterbitkan untuk desa, dengan domain dsbnya yg ditentukan. Yaitu pemesanan tetap untuk desa, bukan mitra. Mitra hanya sebagai pihak penjual.

**Comment by agungsugiarto** [comment]
saya rasa aplikasi invoice ini bisa dipakai pak https://github.com/crater-invoice/crater

**Comment by eddieridwan** [comment]
@agungsugiarto untuk kasus mitra, faktur pada desa bukan urusan OpenDesa. Itu urusan mitra dengan desa. Justru maksud issue ini adalah supaya faktur `tidak` ditampilkan.

**Comment by devrakapriyo** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/124
